### ISSUE TITLE
malli.provider/provide not inferring uuid or inst

### ISSUE THREAD

**Issue by boxxxie** [metosin/malli#101]
i know `inst?` isn't part of the default preds, but `uuid?` is.

when m/provide encounters a `#uuid "db0d62d0-f9c2-11e9-a9c8-4e1c82be3afd"` it outputs it as is in the inferred schema, as opposed to `uuid?`

**Comment by ikitommi** [comment]
Both `inst?` and `uuid?` are default preds, will fix this.

**Comment by ikitommi** [comment]
Fixed in master. Changed it so that `any?` and `some?` have lowest priority so if anything else matches, it's used instead.
