### ISSUE TITLE
-simple-schema DEPRECATED warning incorrectly states :compiled instead of :compile

### ISSUE THREAD

**Issue by hti-andre** [metosin/malli#1076]
When calling `-simple-schema` with a function instead of map (old deprecated form), malli prints warning:

```
DEPRECATED: -simple-schema doesn't take fn-props, use :compiled property instead
```

However, the correct property name is `:compile`.

**Comment by ikitommi** [comment]
PR welcome to fix this

**Comment by frenchy64** [comment]
https://github.com/metosin/malli/commit/9b469dec4d46adb69c83f489b0a64edd35d0106e
