### ISSUE TITLE
malli.swagger generates null definitions

### ISSUE THREAD

**Issue by jkxyz** [metosin/malli#1134]
The following line in `malli.swagger` always sets `:definitions` to `nil`. This causes some validations of the Swagger definition to fail (in my case, Microsoft Power Automate doesn't accept it). It should only update the `:definitions` key if any definitions are present. 

https://github.com/metosin/malli/blob/711ca00aab1d2f7a4b51bb813ca3d4846affc0d7/src/malli/swagger.cljc#L191

**Comment by opqdonut** [comment]
Thanks for noticing that! Should be easy to fix – I'm working on it.

**Comment by jkxyz** [comment]
Thanks for the quick fix!
