### ISSUE TITLE
Predicate schemas should emit minimum and maximum values in json schema

### ISSUE THREAD

**Issue by Sardtok** [metosin/malli#1139]
Using `:double` and `number?` should produce the same json schemas, but `number?` ignores the schema properties and only outputs a type of "number", while `:double` copies and renames the `:min` and `:max` keys.

Came across this when I tried using `number?`, and was confused why the min and max values didn't show up in the openapi schema.

`number?`: https://github.com/metosin/malli/blob/dcfc4bab83383e6b938dd1e0a990e814c9694fb9/src/malli/json_schema.cljc#L38

`:double`: https://github.com/metosin/malli/blob/dcfc4bab83383e6b938dd1e0a990e814c9694fb9/src/malli/json_schema.cljc#L171-L173

The same goes for `double?`, `float?`, `int?`, `integer?`, etc.

Moving the minmax-properties function prior to the definition of accept, and using it for all types that support some kind of minimum and maximum should fix this.

**Comment by Sardtok** [comment]
It's easy enough to implement in the json schemas, but validation doesn't enforce min and max for these predicate schemas. This could be fixed in core, but it would change semantics for these predicate schemas.

**Comment by opqdonut** [comment]
Yeah predicate schemas like `double?` can't really access the schema properties currently, and it would perhaps be surprising to some users if they did. We recommend using `:double` etc. instead.

**Comment by opqdonut** [comment]
See also: #1092

**Comment by Sardtok** [comment]
Following the various issues back in that PR shows this is a duplicate of #327.
