### ISSUE TITLE
Define Child/Parent relationship to Schemas

### ISSUE THREAD

**Issue by ikitommi** [metosin/malli#120]
If schemas knew their parent, we would be able to do:

* use properties of mother in children, e.g. error definitions (#86) 
```clj
;; use error message of a parent (here: map-entry schema)
[:map [:x {:error/message "not an int"} int?]]
```

* use mother for complex transformations #119 

Is this good or bad?

**Comment by rschmukler** [comment]
Just echoing some conversation seen in other issues.

For complex transformations, having interceptors (#122, #114) takes care of most things. Any transformer that requires parent access can simply become an `:after` transformer on the parent type. I will admit that this, theoretically, doesn't compose as well, nor remain as focused - however I can't think of any _real_ use cases where this ends up being a big deal.

**Comment by flow-danny** [comment]
I think I have a use-case for this. 

In `reitit` nesting of routes allows one to define what sub-routes share access roles. I would like to define in a similar way the access level for a group of attributes. Then I could filter/transform data (anonymize, or omit keys) based on the user access level.

**Comment by ikitommi** [comment]
#212 is merged in master. Is allows all but error messages to be read from entry schemas.

```clj
(require '[malli.json-schema :as json-schema])

(json-schema/transform
  [:map
   [:x {:json-schema/example 42} int?]
   [:y {:json-schema {:type "string"}} [:fn (fn [x] (string? x))]]])
;{:type "object"
; :properties {:x {:type "integer"
;                  :format "int64"
;                  :example 42}
;              :y {:type "string"}}
; :required [:x :y]}
```

because of that, we don't need childs to know about their parents.
