### ISSUE TITLE
`:map-of` encodes keys as strings

### ISSUE THREAD

**Issue by rschmukler** [metosin/malli#131]
Right now `:map-of` is [hard-coded](https://github.com/metosin/malli/blob/master/src/malli/core.cljc#L350) to call a key transformer with the `keyword->string` value. This means that custom transformers need to be aware of whether they are called from a `map-of` and explicitly handle cases where they are coerced to a string before hand.

I found this behavior really surprising.Is there a reason for it? Happy to submit a PR to remove it or perhaps move it to an `after` of the `:map-of` json transformer?

**Comment by ikitommi** [comment]
Bug, PR welcome!
