### ISSUE TITLE
Use default value in schema

### ISSUE THREAD

**Issue by JohanCodinha** [metosin/malli#143]
Given the following schema
[:map [:weight-unit {:default :newton} keyword?]]
 I wish to use the supply :default value when encoding/decoding fail.

**Comment by ikitommi** [comment]
This would require a way to add a `:default-encoder` and `:default-decoder` info into Transformer options map that is used if no schema-based is found. With that, one could say something like:

```clj
(m/decode
  [:map [:weight-unit {:default :newton} keyword?]]
  {}
  (mt/default-transformer {:add-missing-keys true}))
; => {:weight-unit :newton}
```

**Comment by ikitommi** [comment]
WIP:

```clj
(m/decode
  [:map
   [:a [int? {:default 1}]]
   [:b [:vector {:default [1 2 3]} int?]]
   [:c [:map {:default {}}
        [:x [int? {:default 42}]]
        [:y int?]]]
   [:d [:map
        [:x [int? {:default 42}]]
        [:y int?]]]
   [:e int?]]
  {}
  mt/default-value-transformer)
;{:a 1
; :b [1 2 3]
; :c {:x 42}}
```

* `mt/default-value-transformer` uses `:default` property value if value `nil`
* pull map child schemas automatically and adds the child has `:default` and key is not present
* maps are not added unless explicitly marked with `:default`

Have a spike on this.

**Comment by JohanCodinha** [comment]
So simple, really liking it.
A more generic transformer seems missing or I might not be aware of it, I just fell like when encoding or decoding data it could be use full to access data from the schema, for something like JSON-LD for example.

**Comment by ikitommi** [comment]
Any transformer can access the schema, at `:compile` time. Here's the upcoming default-transformer impl:

```clj
(def default-value-transformer
  (let [get-default #(some-> % m/properties :default)]
    (transformer
      {:default-decoder {:compile (fn [schema _]
                                    (if-let [default (get-default schema)]
                                      (fn [x] (or x default))))}}
      {:decoders {:map {:compile (fn [schema _]
                                   (let [entries (:entries (m/-parse-keys (m/children schema) nil))
                                         defaults (->> entries
                                                       (keep (fn [[k _ v]]
                                                               (if-let [default (get-default v)]
                                                                 [k default])))
                                                       (into {}))]
                                     (if (seq defaults)
                                       (fn [x]
                                         (if (map? x)
                                           (reduce-kv
                                             (fn [acc k v]
                                               (if-not (contains? x k)
                                                 (assoc acc k v) acc))
                                             x defaults)
                                           x)))))}}})))
```

* it is a chain of 2 anonymous transformers:
  * first one looks at schema properties **for all schemas** and fills the default value if set
  * second one only affects `:map` schemas, adds missing keys if value has default, but is not defined

I think this is kinda generic. If not, happy to hear how to make it better.
