### ISSUE TITLE
malli.error/humanize should default to {:wrap :message} option

### ISSUE THREAD

**Issue by ikitommi** [metosin/malli#157]
I think most/99% of the cases the user wan't to add the `{:wrap :message}` option to `malli.error/humanize`. We should use that as a default and for the 1%(?) of the case, one can say `{:wrap identity}`. Also, the option could be named `:identity`.

**Comment by rschmukler** [comment]
Voting for `{:wrap identity}` since it allows the flexability of using other functions (vs. `:identity true` which doesn't).
