### ISSUE TITLE
Should malli have a default mutable registry as an option? 

### ISSUE THREAD

**Issue by eoliphan** [metosin/malli#177]
Per the docs, it's obviously super easy to create your own, though it's it little bit of a pita to pass your custom registry around everywhere, I just created my own wrappers.    Just wondering, given that Malli is going to be attractive to both Schema and spec users, might be nice to have 'spec style' out of the box.

**Comment by ikitommi** [comment]
Hear you. What if there was `DefaultOptionsProvider` protocol with `-get-default-options` fn, that is called by all public functions internally. The default impl would return the immutable `{:registry default-registry}`, but there could be an mutable variant, easy to swap in, **once**, either via a env/system prop or just via a helper fn.

**Comment by rschmukler** [comment]
I'd also like to suggest that we consider supporting dynamic variables for a default registry / extensions. This serves as a middle ground (and perhaps shouldn't be mutually exclusive to a mutable variant) of having explicit overrides, while also not requiring options be threaded to deeply nested functions.

Note that this is just a suggestion for conscious consideration - dynamic scope has some sharp edges with multithreaded programs (although most of clojure's concurrency built-ins use `bound-fn` under the hood to alleviate this) and so it may not be worth adding.

eg:

```clj
(binding [m/*registry-extensions* {:account/user (user-schema)}]
   (mt/transform data schema))
```

**Comment by ikitommi** [comment]
#188 starting to look good IMO. comments welcome.

**Comment by ikitommi** [comment]
and for dynamic scope - has bitten me few times, the suggested architecture would support that, but in the user-space, not in malli.core.

**Comment by ikitommi** [comment]
I rethought about it and agree it's a good idea to have in the the core - and it's definitely subject to DCE. Moved the registry composition into a separate `mr/composite-registry` and added a `dynamic-registry` as you suggested. So, this is possible after the PR:

```clj
(require '[malli.core :as m])
(require '[malli.registry :as mr])

;; bring your own evil
(def registry (atom {}))

(defn register! [type schema]
  (swap! registry assoc type schema))

;; managed registry initialized with
;; - cljs: :closure-defines {malli.registry/type "managed"}
;; -  clj: :jvm-opts ["-Dmalli.registry/type=managed"]
(mr/set-default-registry!
  ;; linear search
  (mr/composite-registry
    ;; immutable registry
    {:map (m/-map-schema)}
    ;; mutable (spec-like) registry
    (mr/mutable-registry registry)
    ;; on the perils of dynamic scope
    (mr/dynamic-registry)))

;; like a boss
(register! :maybe (m/-maybe-schema))

;; ☆.。.:*・°☆.。.:*・°☆.。.:*・°☆.。.:*・°☆
(binding [mr/*registry* {:string (m/-string-schema)}]
  (m/validate
    [:map [:maybe [:maybe :string]]]
    {:maybe "sheep"}))
; => true
```
