### ISSUE TITLE
Sequence/regex schemas

### ISSUE THREAD

**Issue by ikitommi** [metosin/malli#180]
From slack:

like clojure.spec.alpha/conform, there could be something for that? Explain could return either failures or real values if no errors exist.

```clj
 (->
   [:cat
    [:x int?]
    [:y int?]
    [:rest [:* string?]]]
   [1 2 "kikka" "kukka"]
  (m/explain)
  (mu/humanize))
 ; {:x 1
 ;  :y 2
 ;  :rest ("kikka "kukka")}
```

and/or, an anonymous variant:

```clj
 (m/valid?
   [:cat int? int? [:* string?]]
   [1 2 "kikka" "kukka"])
 ; => true
```

using for example https://github.com/cgrand/seqexp under the hoods

**Comment by green-coder** [comment]
When designing it, the scenario of implementing the equivalent of `clojure.alpha.spec/unform` might also be considered.

For info, I would use both conform and unform if mali has it.

**Comment by ikitommi** [comment]
Related issues:
* https://github.com/cgrand/seqexp/issues/11
* https://github.com/cgrand/seqexp/issues/9

**Comment by ikitommi** [comment]
Initial internal impl done, just 123loc. need to add tests and figure out how to expose the parsing api in general. 

<img width="521" alt="Screenshot 2020-09-10 at 20 41 31" src="https://user-images.githubusercontent.com/567532/92779756-02ca7000-f3ab-11ea-8e48-dbe29458ee67.png">

**Comment by ikitommi** [comment]
Master!
