### ISSUE TITLE
About map key type

### ISSUE THREAD

**Issue by piotr-yuxuan** [metosin/malli#189]
As all the example of this (rather well-designed) library show map keys as keywords. However string is also allowed as well as some other types:

``` clojure
(is (malli.core/validate
      [:map
       ["status" [:enum "ok"]]
       [1 any?]
       [nil any?]
       [::a string?]
       [:a number?]]
      {"status" "ok"
       1 'number
       nil :yay
       ::a "properly awesome"
       :a 1}))
```

This versatility is really amazing.

I believe it could be emphasized in the readme as it might prove quite a killer feature for some users. For example, this allows to enforce some shape over data coming from json, where all keys are strings with no need to keywordize keys.

Similar to https://github.com/metosin/malli/issues/14 at least in the title.

**Comment by ikitommi** [comment]
Would you be interested in adding a small sample into the README from this? Also, don't think there are any tests for this, PR would be most welcome.

**Comment by ikitommi** [comment]
copied your example into README. thanks!
