### ISSUE TITLE
(m/decode int? "23.abc" mt/string-transformer) gives 23 Integer on cljs on clj "23.abc"

### ISSUE THREAD

**Issue by geraldodev** [metosin/malli#199]
Hi,

```
(require '[malli.core :as m])
(require '[malli.transform :as mt])
(m/decode int? "23.abc" mt/string-transformer)
```
"23.abc" on clojure because it is invalid
23 Integer on clojurescript which appears to be wrong.

**Comment by ikitommi** [comment]
I don't think it's right. PR welcome to fix this.

**Comment by geraldodev** [comment]
https://github.com/metosin/malli/pull/200

**Comment by ikitommi** [comment]
This is fixed in master
