### ISSUE TITLE
Support recursion in Malli Schema definitions

### ISSUE THREAD

**Issue by ikitommi** [metosin/malli#20]
Registry should support recursion, e.g. 

```clj
{::age int?
 :child-age [:and ::age [:> 18]] ;; should be expanded
 :child [:map 
         [:name string?] 
         [:age :child-age] 
         [:friends [:set :child]]]} ;; recursion
```

**Comment by RafaeLeal** [comment]
Hello!
I have a different proposal, to be more flexible. So we don't require to be on registry to support recursion.
https://github.com/metosin/malli/pull/117

**Comment by ikitommi** [comment]
merged in master
