### ISSUE TITLE
:default false doesn't work

### ISSUE THREAD

**Issue by kwrooijen** [metosin/malli#218]
```clojure
(require '[malli.core :as m])
(require '[malli.transform  :as mt])
(m/decode [:map [:person/verified [:and {:default false} boolean?]]] {} mt/default-value-transformer)
; => {}
(m/decode [:map [:person/verified [:and {:default true} boolean?]]] {} mt/default-value-transformer)
; => #:person{:verified true}
```
I expected the first decode to return `#:person{:verified false}`

This is probably because `:default` is checked somewhere to see if it's a truthy value. The question is, is this a bug, or intended? Seems a bit misleading. Maybe we should check if the key `:default` exists rather than check if it's a truthy value?

**Comment by rschmukler** [comment]
In an attempt to verify (and fix) this, I added a test to `transformers_test.cljc` that looked like:

```clj
(testing "falsey defaults"
    (let [schema [:map [:person/verified [:and {:default false} boolean?]]]]
      (is (= {:person/verified false}
             (m/decode schema {} mt/default-value-transformer)))))
```

The test passed for me. Which version of malli did you run into this on? Can you confirm that it doesn't behave as expected on master.

**Comment by kwrooijen** [comment]
You're right, it works. I should've updated before reporting this issue, sorry about that. Funny how it was fixed so recently, thanks!
