### ISSUE TITLE
Improve string validation humanized messages

### ISSUE THREAD

**Issue by ivos** [metosin/malli#225]
Without `min` and/or `max`, when the value is not a String, it reports correctly `"should be a string"`:

```Clojure
(malli.error/humanize (malli.core/explain [:string] "Bla"))
=> nil
(malli.error/humanize (malli.core/explain [:string] 1))
=> ["should be a string"]
```

With `min` and/or `max`, when the value is not a String, it reports a message indicating invalid length of the String:

```Clojure
(malli.error/humanize (malli.core/explain [:string {:max 3}] "Bla"))
=> nil
(malli.error/humanize (malli.core/explain [:string {:max 3}] "Gogo"))
=> ["should be at most 3 characters"]
(malli.error/humanize (malli.core/explain [:string {:max 3}] 1))
=> ["should be at most 3 characters"]
```

I believe this is misleading, and the `"should be a string"` message should be reported in this case, too.

(Thanks for the malli library! Finally something that can actually be used for user input validation in Clojure.)

**Comment by ikitommi** [comment]
PR welcome
