### ISSUE TITLE
Walking data of recursive schema and generate unique key for each map

### ISSUE THREAD

**Issue by lins05** [metosin/malli#244]
I have a recursive schema - think about a file system, where there are directories as maps, files as leaves, and sub-directories as child maps.

For each directory (map), I want to generate a unique key for it based on its path in the whole tree.

There is no way of doing this using malli's walker - it walks the schema, not the actual data. So for now the only way is to walk the actual data manually.

But since malli is already walking the data for schema validation/conforming, I hope I can achieve the goal without waking it again.

**Comment by ikitommi** [comment]
I tried to find an elegant solution for this, but it would add a lot of extra parameter passing just to support this case. I think doing a custom `pre-walk` is better for this. Cheers.
