### ISSUE TITLE
`json-transformer` doesn't convert non-string keys

### ISSUE THREAD

**Issue by schmee** [metosin/malli#259]
As discussed with @ikitommi on Slack. Example:

```clj
(def schema [:map-of int? uuid?])
(def m {"0" "2ac307dc-4ec8-4046-9b7e-57716b7ecfd2"
        "1" "820e5003-6fff-480b-9e2b-ec3cdc5d2f78"})
(m/decode schema m mt/json-transformer)
user=> {"0" #uuid "2ac307dc-4ec8-4046-9b7e-57716b7ecfd2"
        "1" #uuid "820e5003-6fff-480b-9e2b-ec3cdc5d2f78"}
```

The keys are not converted since JSON supports ints, but it doesn't support non-string keys. It would make sense if the keys were converted to ints in this case.

**Comment by ikitommi** [comment]
I think we need to add a new target for a map-keys, so we can apply normal string-transformation for it. shouldn't be a big change.
