### ISSUE TITLE
ClassCastException during `malli.error/humanize`

### ISSUE THREAD

**Issue by kmrozek-shareablee** [metosin/malli#265]
I've got an issue with humanize in this code:
```
(-> (m/explain [:sequential [:map [:x [:sequential [:map [:y number?]]]]]]
               '({:a 10}
                 {:b 10}))
    (me/humanize))
```

It seems that the problem is with `-put` function. It cannot handle lists properly.

**Comment by ikitommi** [comment]
thanks for reporting. should be fixed in master. could have retained the original sequence data structure, but that would be quite inefficient, so, it returns now a vector instead:

```clj
[{:x ["missing required key"]}
 {:x ["missing required key"]}]
```

is this ok/expected?

**Comment by kmrozek-shareablee** [comment]
Yes, it's ok. Thanks.
