### ISSUE TITLE
cljdoc for Malli is broken

### ISSUE THREAD

**Issue by miikka** [metosin/malli#274]
cljdoc is unable to build documentation for malli - see https://cljdoc.org/d/metosin/malli/0.1.0/. There are two independent issues:

* [SCM info is missing](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/faq.md#how-do-i-set-scm-info-for-my-project) from pom.xml. Note that `<tag>` information needs to be updated before every release.
* pom.xml needs to be included in the jar file for cljdoc to see the dependency information (may be fixed in future: https://github.com/cljdoc/cljdoc-analyzer/issues/29). Instructions on how to do this are here: https://github.com/cljdoc/cljdoc/issues/404#issuecomment-656559303 and https://github.com/cljdoc/cljdoc/issues/404#issuecomment-656864348

**Comment by ikitommi** [comment]
just adding SCM info produced this: https://cljdoc.org/d/metosin/malli/0.2.0. There is some error still, but basic docs work ok now? There is no automation in setting the version for the SCM info.

**Comment by miikka** [comment]
Okay, now the article docs are generated but the namespace documentation is still missing. And yeah, the SCM version info updates should be automated or they will be forgotten.

To generate the namespace docs, the pom has to be included in the .jar file (the second point of my original comment).

**Comment by ikitommi** [comment]
next.jdbc might have a good config for this: https://github.com/seancorfield/next-jdbc.

**Comment by miikka** [comment]
What next.jdbc does is that it uses [depstar](https://github.com/seancorfield/depstar) instead of pack. That's probably a good idea for Malli as well since depstar has better pom.xml integration in general.

**Comment by rschmukler** [comment]
You might also like [pablo](https://github.com/teknql/pablo). I personally use it for [wing](https://github.com/teknql/wing) which is a mono-repo that breaks into smaller libraries. No opinion at all - pablo is definitely extremely early so you might want something with more field usage as well. Still, given the monorepo support, it might be something you'd like since malli being broken out into smaller libraries has been considered in the past.

**Comment by miikka** [comment]
cljdoc/cljdoc-analyzer#29 got fixed, so the namespace documentation generation works now. The release setup still needs work but cljdoc works now, so I'm closing this issue.
