### ISSUE TITLE
Which Java versions are supported?

### ISSUE THREAD

**Issue by miikka** [metosin/malli#279]
Proposal: explicitly support the current LTS releases Java 8 and 11, and the latest release (15).

I'm not sure who long we should continue to support Java 8, but it's [widely used in Clojure community](https://clojure.org/news/2020/02/20/state-of-clojure-2020) (search Java 8) and I don't see a pressing need to drop the support. Maybe reconsider in a year or two if the situation changes.

* [ ] This should be documented in the documentation.
* [ ] CI should be configured to run the tests with the supported versions.

**Comment by ikitommi** [comment]
Sounds good.
