### ISSUE TITLE
key-transformer is not recursive

### ISSUE THREAD

**Issue by ixemad** [metosin/malli#290]
I noticed that the result of the example for `key-transformer` diverged from the one documented in [Value Transformation](https://github.com/metosin/malli#value-transformation). In my case, the transformation does not deepen into the `address` map.
```clojure
(m/decode
   Address
   {:id "Lillan",
    :tags ["coffee" "artesan" "garden"],
    :address {:street "Ahlmanintie 29"
              :city "Tampere"
              :zip 33100
              :lonlat [61.4858322 23.7854658]}}
   (mt/key-transformer {:decode name}))
;; => {"id" "Lillan", 
;;     "tags" ["coffee" "artesan" "garden"], 
;;     "address" {:street "Ahlmanintie 29", 
;;                :city "Tampere", 
;;                :zip 33100, 
;;                :lonlat [61.4858322 23.7854658]}}
```

My example was executed with malli `0.2.1 and sci `0.1.1-alpha.7`.

**Comment by ikitommi** [comment]
oh. The example should be changed. `decode` is a process of transforming invalid values into valid ones. In the example, the keys don't match after the `name` - there is no `:address` to recur to. The example could have string keys and `keyword` as the decoding fn and it would work as expected.

One can configure the key transformation to happen in the `:leave` phase and, could add options & docs to make it easy to do.

**Comment by ixemad** [comment]
Not sure if I completely get you, @ikitommi. At least, I was able to reproduce the original result with `m/encode`.
```clojure
(m/encode
 Address
 {:id "Lillan",
  :tags ["coffee" "artesan" "garden"],
  :address {:street "Ahlmanintie 29"
            :city "Tampere"
            :zip 33100
            :lonlat [61.4858322 23.7854658]}}
 (mt/key-transformer {:encode name}))
;; -> {"id" "Lillan",
;;     "tags" ["coffee" "artesan" "garden"],
;;     "address" {"street" "Ahlmanintie 29",
;;                "city" "Tampere",
;;                "zip" 33100,
;;                "lonlat" [61.4858322 23.7854658]}}
```

**Comment by nilern** [comment]
Indeed `encode` should have been used (see #352). Simplifying a lot, `encode` is bottom-up and `decode` top-down.
