### ISSUE TITLE
Not working with babashka

### ISSUE THREAD

**Issue by lucywang000** [metosin/malli#302]
```clojure
user=> (require '[malli.core :as ma])
Could not resolve symbol: deftype [at borkdude/dynaload.cljc:4:2]
```

I made several quick fixes here to make the `require` work: https://github.com/lucywang000/malli/commit/1f46840

But it still can't run the simplest validation:

```clojure
user=> (require '[malli.core :as ma])
nil
user=> (ma/validate int? "1")
java.lang.NullPointerException [at malli/core.cljc:1003:7]
```

Looks like something wrong with babashka's defprotocol implementation.

**Comment by ikitommi** [comment]
Would be great if it worked. Help most welcome. subscribed the https://github.com/borkdude/babashka/issues/647.
