### ISSUE TITLE
Recursive Schema Generation

### ISSUE THREAD

**Issue by cartesian-theatrics** [metosin/malli#307]
Hello, I'm running into some issues trying to generate data matching a recursive schema:

```clojure
(mg/sample [:schema {:registry {::A
                                [:tuple
                                 [:= ::a]
                                 [:vector [:ref ::A]]]}}
            ::A]
           {:size 10})

;; => ([:user/a []]
;; [:user/a []]
;; [:user/a []]
;; [:user/a []]
;; [:user/a []]
;; [:user/a []]
;; [:user/a []]
;; [:user/a []]
;; [:user/a []]
;; [:user/a []])
```

It never generates examples beyond a depth of zero. However, the ping/pong example in the README does seem to generate examples with nested data. The problem seems to be related to generating a `:vector` of recursive references.

Regards,
John

**Comment by ikitommi** [comment]
thanks! should be fixed in master.
