### ISSUE TITLE
Question regarding public vs. private API

### ISSUE THREAD

**Issue by DerGuteMoritz** [metosin/malli#308]
First of all, thanks a lot for your effort on Malli!

I have a question regarding the API naming convention: A lot of vars in `malli.core` are prefixed with a dash. Their definitions appear before this comment:

```
;;
;; public api
;;
```

So one could assume that they are considered internal. However, `README.md` contains various references to such vars (all of them schema constructors AFAICT). So my question is: Should I be cautious when using those vars or are they really part of the public API? If so, is that true for all of them? My question was prompted specifically because I wanted to use `-reference?`.

Thanks!

**Comment by ikitommi** [comment]
Hi. The naming convention is described in the README: https://github.com/metosin/malli#alpha.

e.g. `-reference?` is part of the advanced/extender api, no plans to break it. If, for some unknown reason, we must break it, it change will be covered in the CHANGELOG.

**Comment by DerGuteMoritz** [comment]
Ah, thanks a lot! Been a while since I read that bit and clearly I didn't memorize it well enough. Sorry for the noise! :pray:
