### ISSUE TITLE
Latest released version cannot be compiled in CLJS

### ISSUE THREAD

**Issue by Jeiwan** [metosin/malli#313]
We're using Malli 0.2.1 (latest released version so far) and cannot use it in ClojureScript. We're getting this error when trying to compile with ShadowCLJS:
```
Closure compilation failed with 3 errors
--- malli/core.cljc:2835
Parse error. Duplicate parameter name "fwrap__$1"
--- malli/core.cljc:2848
Parse error. Duplicate parameter name "fwrap__$1"
--- malli/core.cljc:2854
Parse error. Duplicate parameter name "fwrap__$1"
```

I see that this function was removed but it was probably present in the released version.

We're using ShadowCLJS 2.8.64 and Node 12.18.4. We're building a release with:
```
npx shadow-cljs release app
```

**Comment by miikka** [comment]
I'm not able to reproduce this with shadow-cljs 2.11.8. Could you try to upgrade your shadow-cljs version? Or could you produce a repository to reproduce this problem? Also, are you really sure you're using malli 0.2.1? As far as I can tell, malli 0.2.1 does not include the string `fwrap`

**Comment by Jeiwan** [comment]
Sorry, that was an older Malli version (0.0.1-SNAPHOT). Thanks for the response!
