### ISSUE TITLE
Flaky randomized tests in function-schema-test

### ISSUE THREAD

**Issue by miikka** [metosin/malli#341]
Sometimes there are test failures that go away when you re-run the tests: https://github.com/metosin/malli/runs/1727181659?check_suite_focus=true#step:5:184

https://github.com/metosin/malli/blob/3fff19bd224b0490c120bd381fdeceb086ea2483/test/malli/core_test.cljc#L1730-L1760

Two things need to be done:

1. The source of randomness need to be instrumented so that whenever there is a failure, we can re-run the test, just like test.check prints the seed when there is a failing test. Maybe it's possible to directly use [defspec](https://clojure.org/guides/test_check_beginner#_defspec)?
2. The test should be fixed.

**Comment by frenchy64** [comment]
Fixed by https://github.com/metosin/malli/pull/1040
