### ISSUE TITLE
Provide utility for normalizing schemas.

### ISSUE THREAD

**Issue by DrBuchkov** [metosin/malli#344]
Provide utility for normalizing schemas by adding 'nil' or an empty map in schema forms where options are ommited

For example normalizing forms of the shape:

```clojure 
[:id uuid?] 
````
 To

```clojure 
[:id nil uuid?] 
````

Or
```clojure 
[:id {} uuid?] 
````
This will facilitate the development of tools that parse malli schema forms by not having to handle the possibility of the two different shapes.

**Comment by ikitommi** [comment]
It would be easy to add a helper for this, but curious about your use case: why do you want to go parse the malli hiccup format? There are lot of tools already for reading and transforming the parsed schema, using `Schema` and `LensSchema` protocols behind the schemas.

**Comment by ikitommi** [comment]
Anyway, added example how to do this into [tips](https://github.com/metosin/malli/blob/master/docs/tips.md#normalizing-properties).

```clj
(require '[malli.core :as m])
(require '[malli.util :as mu])

(defn normalize-properties [?schema]
  (m/walk
    ?schema
    (fn [schema _ children _]
      (if (vector? (m/form schema))
        (into [(m/type schema) (m/properties schema)] children)
        (m/form schema)))))

(normalize-properties
  [:map
   [:x int?]
   [:y [:tuple int? int?]]
   [:z [:set [:map [:x [:enum 1 2 3]]]]]])
;[:map nil
; [:x nil int?]
; [:y nil [:tuple nil int? int?]]
; [:z nil [:set nil
;          [:map nil
;           [:x nil [:enum nil 1 2 3]]]]]]
```
