### ISSUE TITLE
Instrument schematized vars

### ISSUE THREAD

**Issue by ikitommi** [metosin/malli#349]
Way to turn schematized functions into wrapped ones that do runtime validation for  input & outputs. See https://github.com/jeaye/orchestra

**Comment by ikitommi** [comment]
see #369.

**Comment by ianffcs** [comment]
Hi, I was wondering with @narocath and @LeaveNhA about on how move forward on implementing this feature, we got into those 
questions:

 1. Do we need to add the functions to the default-registry? or create a separate registry for functions?
 2. Do we need another m/=> like macro for register data-validators? (like m/def)
 3. Do we need to make a global atom for the default-registry? (to swap and add the functions-schemas / to swap and add data-validators schemas)
 4. Can we use nsed keyowrds for registering function-schemas / data-validator schemas?
 5. Do we want a switch to enable a type of instrumentation of malli?

**Comment by ikitommi** [comment]
Hi, sorry for keeping you waiting. My 2 cents:

1. all function (var) definitions should be in the `m/-function-schemas*` (e.g. via `m/=>`) and instrument should use that
2. have wanted to postpone that for malli 1.0.0, or add an optional `malli.global` ns before that. Not clear yet
3. see 1, function schemas already have a global registry
4. let's start with just instrumenting vars?
5. maybe later, could start with just `malli.instrument/instrument!`

the api:

* `malli.instrument` sounds like a good idea - all optional
* `instrument!` and `uninstrument!` could be the only public api
    * 0-arity => everything
    * 1-arity => options-map, which should later have namespaced options on how to do things: fail on error, just log errors, filter based on schema properties, inputs, outputs or both, error printer, ...
* nothing fancy for error printing needed now, just bare-bones.

the bare minimum would be (adopted from https://github.com/setzer22/malli-instrument):

```clj
(require '[malli.core :as m])
(require '[malli.instrument :as mi])

(m/=> foo [:=> [:cat int? int?] string?)
(defn foo [x, y]
  (+ x y))
  
(mi/instrument!)

(foo 1 2) 
;; miu/-fails with :malli.instrument.invalid-output {:error ["should be a string"], :value 3} 
```

what do you think?

**Comment by viebel** [comment]
Is someone working on this issue?

**Comment by ikitommi** [comment]
this seemed stalled so started working on this, see #471.

**Comment by ikitommi** [comment]
#471 merged in master. the new function schema guide found here: https://github.com/metosin/malli/blob/master/docs/function-schemas.md. This will be released after vacations along with many small changes. 

Testing, feedback an improvements most welcome.

**Comment by viebel** [comment]
That's awesome @ikitommi.
Where will you be back from vacations?
