### ISSUE TITLE
Question: Way to add custom predicates

### ISSUE THREAD

**Issue by jeans11** [metosin/malli#35]
Hi!
I'm trying your lib and I'm wondering how add custom predicates.

Is this the way to add custom predicates?

```clojure
(defn size-between
  [s a b]
  (< a (count s) b))

(defn small-string?
  [s]
  (size-between s 1 10))

(deftest lib-test
  (let [registry
        (merge
          m/comparator-registry
          m/base-registry
          m/predicate-registry
          {small-string? (m/fn-schema :small-string? small-string?)})
        schema [:and string? small-string?]]
    (is (false? (m/validate schema "aaaaaaaaaaaaaaaaaaaaaaaaaa" {:registry registry})))))
```

**Comment by ikitommi** [comment]
That is one way to do it, having all the schemas in a registry allows one to serialize & deserialize the schemas using it. If you don't need that, you can also just create and inline `Schema` instances. Currently, there is no helper for that (`fn-schema` returns a `IntoSchema` instance), but there could be a `:fn` wrapper for that:

```clj
(m/validate [:fn small-string?] "aaa")
; => true
```

for one-way serialization, there could be a property `:form` to tell how it's written:

```clj
(m/form [:and string? [:fn {:form 'small-string?} small-string?]])
; => [:and string? small-string?]
```

Ideas and comments most welcome.

**Comment by ikitommi** [comment]
Also, as the `:registry` option is a function of `name->IntoSchema`, one could provide a custom implementation which in case of miss, checks if the input was a function and creates a anonymous function schemas out of it - all predicates would just work:

```clj
(def my-registry-auto-wrapping-functions-as-schemas ...)

(m/validate small-string? "aaa" {:registry my-registry-auto-wrapping-functions-as-schemas)
; => true
```
could add an example out of this into the README. Not likely to be a built-in feature.

**Comment by ikitommi** [comment]
One more thing... the `validate`, `explain`, `transform` etc. are for convenience: they first compile the schemas and functions and then invoke them once (and lose the compilation result). To get also stellar perf, you should use `validator`, `explainer`,  `transformer` functions that just do the compilation step and return an optimized function for the actual job. All compiled functions are all pure.

Cheers.

**Comment by jeans11** [comment]
Thanks @ikitommi

**Comment by ikitommi** [comment]
Will keep this open until a helper is done.

**Comment by ikitommi** [comment]
There is also a https://github.com/borkdude/sci, which could be used, if you know what you are doing:

```clj
(def schema (m/fn #(< 10 % 100))
 
(m/validate schema 11)
; => true

(-> schema
    (pr-str)
    (edn/read-string)
    (m/schema)
    (m/validate 11)
; => true

(m/form schema)
; => [:fn {:sci "#(< 10 % 100)"}]
```

**Comment by ikitommi** [comment]
or just as strings:

```clj
(m/validate [:sci "#(< 10 % 100)"])
; => true
```

**Comment by ikitommi** [comment]
these both work now:

```
;; string
(m/validate [:fn "#(< 10 % 100)"] 11)
; => true

;; form
(m/validate [:fn '#(< 10 % 100)] 11)
; => true
```

it's also guarded against the non-termination:

```clj
(m/validate [:fn '#(if (< % (apply max (range))))] 1)
; => false
```

will keep this still open and add a easy way to register/use custom vars.

**Comment by jeans11** [comment]
Nice work!
Just for my curiosity :) Why use string or quoted code instead of plain clojure function?

**Comment by ikitommi** [comment]
Great question. They are now portable: functions can be sent over wire, applied on browser/cljs, saved & loaded to the db etc. Still need to add support for easy usage of non-serializable functions. But it's a different contract.

**Comment by jeans11** [comment]
I didn't see it like that but it's very interesting!
Thank for the answer!

**Comment by ikitommi** [comment]
Summing up the options:

### 1) Break the contract of "all default schemas are serializable"

* add support for plain Clojure/Script functions to `:fn`
* relatively easy to add custom predcates, but one can't know for sure if a schema graph can be fully serialized or not (without new helpers to know this)

```clj
(defn over18? [x] (> x 18))

(over18? 20)
; => true

[:and int? [:fn over18?]]
```

```clj
;; can be serialized
[:and int? [:fn '#(> % 18)]]

;; can't be serialized
[:and int? [:fn #(> % 18)]]
[:and int? [:fn over18?]]
```
### 2) create a helper `m/defn` &/ `m/fn` to create serializable function schemas

* relatively easy to add new schemas
* could support Schema-like typed syntax
* BAD: one needs to wrap existing functions into these.

```clj
(m/defn over18? [x] (> x 18))

;; works like a normal predicate
(over18? 20)
; => true

;; can be used a schema
[:and int? over18?]
```

### 3) optionally allow any predicate to be used, via custom option

* schema `m/form` could be read from the demunged predicate name
* can be serialized & back within Clojure (but not ClojureScript!)

```clj
(defn over18? [x] (> x 18))

(over18? 20)
; => true

(m/validate over18? 19 {:allow-non-serializable-predicates true})
; => true

(m/form over18?)
; => user/over18?
```

### 4)Don't support

* one needs to add custom predicates into registry before use

**Comment by nilern** [comment]
I prefer 3, as long as it is not too inconvenient.

**Comment by ikitommi** [comment]
The current implementation is 1). One can pass any predicate using `:fn`. Added an issue to check if a schema can be serialized #115 to solve all the evil that spawns from this call.
