### ISSUE TITLE
Generator generation diverges

### ISSUE THREAD

**Issue by nilern** [metosin/malli#359]
While I was trying to describe Malli forms with Malli I noticed that recursive generator generation can diverge:

```clj
(mg/generator
  [:schema {:registry {::schema [:or
                                 [:= :int] [:= :string]
                                 [:cat [:= :and] [:* [:schema [:ref ::schema]]]]
                                 [:cat [:= :or] [:* [:schema [:ref ::schema]]]]
                                 [:tuple [:= :vector] [:ref ::schema]]]}}
   ::schema])
; Execution error (OutOfMemoryError) at malli.generator/-create (generator.cljc:219).
; GC overhead limit exceeded
```

Perhaps `malli.generator` should use `clojure.test.check.generators/recursive-gen` instead of the current ad hoc recursion depth limiting? I don't really get the current limits, so can't really say whether they can be made to work for all schemas.

**Comment by ikitommi** [comment]
There is such a thing? Please.

**Comment by frenchy64** [comment]
Generation now uses `recursive-gen` via https://github.com/metosin/malli/issues/452

**Comment by ikitommi** [comment]
yes, this works now.
