### ISSUE TITLE
Conceptual Feature: value units-of-measure specification and transformation

### ISSUE THREAD

**Issue by dcj** [metosin/malli#417]
This is intended as a conceptual exploration/disucssion regarding the interest-in and suitablity-of potentially extending Malli value schemas to support specification of the units-of-measure, and the transformation of values between different units-of-measure (UoM)

Use case:  I have a key `:speed` its value is specified as a float, and I'd further like to specify that its value is in units of "meters per second", and an external datasource I am interacting with represents speed in "nautical miles per hour", and as an integer.
I'd like to specify the UoM of each, and a UoM transformer could be used to transform values between these representations.

Does this seem like a reasonable thing to explore in the context of Malli?

Existing UoM work/thinking:

- [Chapter 6, 6.2.1, 6.3.1 of Software Design for Flexibility](https://mitpress.mit.edu/books/software-design-flexibility)
- [Frink](https://frinklang.org/)
- [OGC Units of Measure Reccomendation](https://portal.ogc.org/files/?artifact_id=11498)
- [Schema.org Measurement Proposal](https://www.w3.org/wiki/images/4/42/Schema.orgMeasurement.pdf)

**Comment by ikitommi** [comment]
I think malli is a good fit for that. Maybe something like this:

```clj
(require '[malli.core :as m])
(require '[malli.transform :as mt])
(require '[malli.generator :as mg])

(def units
  [{:schema [:int {:min 0, :gen/max 100}]
    :name "meters per second"
    :coerce int
    :multiplier 1}
   {:schema [:double {:min 0, :gen/max 100}]
    :name "nautical miles per hour"
    :coerce double
    :multiplier 0.514444}
   {:schema [:double {:min 0, :gen/max 100}]
    :name "kilometers per hour"
    :coerce double
    :multiplier 0.277778}])

(let [m (->> units (map (juxt :name :multiplier)) (into {}))
      c (->> units (map (juxt :name :coerce)) (into {}))]
  (defn unit->unit [from to]
    (fn [x] (-> x (* (m from)) (/ (m to)) ((c to))))))

(defn unit-transformer [to]
  (mt/transformer
    {:default-decoder
     {:compile (fn [schema _]
                 (when (-> schema m/properties :unit/type (= :unit/any))
                   (fn [[value from]] [((unit->unit from to) value) to])))}}))

(def Speed
  (into [:multi {:dispatch second, :unit/type :unit/any}]
        (for [{:keys [schema name]} units]
          [name [:tuple schema [:= name]]])))

(def Vessel
  [:map
   [:id :uuid]
   [:speed Speed]
   [:history [:map
              [:max Speed]
              [:min Speed]]]])

(mg/generate Vessel {:seed 2})
;{:id #uuid"d3700aea-1375-46e9-b3d7-c852376900c4",
; :speed [1 "meters per second"],
; :history {:max [14.25 "nautical miles per hour"]
;           :min [0.20785999298095703 "kilometers per hour"]}}

(m/decode Vessel *1 (unit-transformer "kilometers per hour"))
;{:id #uuid"d3700aea-1375-46e9-b3d7-c852376900c4",
; :speed [3.5999971200023038 "kilometers per hour"],
; :history {:max [26.39095608723513 "kilometers per hour"]
;           :min [0.20785999298095703 "kilometers per hour"]}}
```

**Comment by dcj** [comment]
Random thoughts:

Maybe there are "equivalents" one could define, e.g. 1 nautical-miie == 1852 meters

In "Software Design for Flexibility" they combine units, so meters-per-second would be something like {:meter 1 :second -1}

**Comment by ikitommi** [comment]
The code above has the equivalents as data (the `:multiplier`) per unit and the schemas and transformations are derived from it.

The units were bundled "meters per second", but you can split them too, e.g. `[1 "meters per second"]` => `{:value 1, :distance-unit "meter", :time-unit "second"}` easily so you derive transformations for "meter per minute" => "nautica miles per nanosecond".

**Comment by ikitommi** [comment]
closing this, seems doable. cheers.
