### ISSUE TITLE
[Feature Request]support async validator in cljs

### ISSUE THREAD

**Issue by yqrashawn** [metosin/malli#426]
Currently, (validate ...) returns a promise if the :pred is a js async function. This works fine if there's a await in the js side.

But the explain will always return nil cause the (validator x) returns a js/Promise.

https://github.com/metosin/malli/blob/fac7b6c21d8abd7fa1f532bb9dca778ab7282e24/src/malli/core.cljc#L339

**Comment by nilern** [comment]
Presumably an async function is impure and impure validator functions seem quite suspicious to me. Are you sure you have to go there?

Making everything (optionally) async would be a lot of work and extra generated JS. And then one might ask why `core.async` or other async libraries or arbitrary monads don't have the same support.

**Comment by yqrashawn** [comment]
That make sense to me. I've managed to make the validator sync. I'll close this issue.
