### ISSUE TITLE
`:re` ignores `:gen/xxx` properties in absence of `:gen/gen`

### ISSUE THREAD

**Issue by helins** [metosin/malli#435]
Something like this will throw `:test-chuck-not-available` on generation:

```clojure
[:re
 {:gen/fmap (fn [x] ...)
  :gen/schema :int}
  #"some-regex"]
```

I guess in Clojurescript it will throw even sooner because it will look for the `:re` method on `-schema-generator` which is only defined on the JVM.

Adding a `:gen/gen` value, even completely unrelated, fixes this. So the problem is broader. It looks like this is due to how `malli.generator/-create`, in absence `:gen/gen`, calls `-schema-generator` even when it is not actually needed.

If you confirm this, I can try to PR a rewrite of `-create`.

**Comment by ikitommi** [comment]
Please do.

**Comment by ikitommi** [comment]
fixed in master
