### ISSUE TITLE
Incorrect docstring for `open-schema`

### ISSUE THREAD

**Issue by fredZen** [metosin/malli#444]
The docstring for `open-schema` says "**Closes** recursively all :map schemas by removing `:closed` property, unless schema explicitely open with `{:closed false}`".

If I’m not mistaken, it should say instead: "**Opens** recursively all :map schemas etc"

https://github.com/metosin/malli/blob/82d6fb6b27ccc4cf9387b5854fb4214ac77a9990/src/malli/util.cljc#L141

**Comment by ikitommi** [comment]
fixed, thanks
