### ISSUE TITLE
Can encode function access more than just the current node?

### ISSUE THREAD

**Issue by boxxxie** [metosin/malli#453]
I have an encoder that requires accessing the original data structure that is being encoded, or access sibling nodes that have already been through encoding.

i'm not sure if this is possible or not, even with multiple encoding steps, unless i write an encoder for the top-level which has access to the complete data structure. (current approach i'm taking)

**Comment by ikitommi** [comment]
currently, there is no state being carried (like with zippers), so not sure how to best do that. There are the `:enter` and `:leave` stages that maybe could be used, but I guess with the current design, it would require multiple sweeps. A simplified example would help to think a solution.

for specific encoding situations, I have found that it might be better to preprocess the schemas. For example, doing a malli -> html form, I created `malli.util/subschemas` helper that flattens the deeply nested schemas into a easily iterable form.

**Comment by eoliphan** [comment]
I ran into something similar, was playing around with using malli to translate to/from datomic conventions for enums. so for a schema like `:my/options [:enum :a :b]` , `:b:` would become `:my.options/b`.  But couldn't figure out how to get the context i needed at encode time.

**Comment by boxxxie** [comment]
@eoliphan i do this successfully.
for encoding datomic enums, i use a compiler, also to note i have to encode sets and single enums differently. i also add custom options to my enums for translation to select/radio web components. also i have a schema transformation (walk) that i do to change malli enums into something that my compiler can better use.

my enum defs look something like this `(defenum)` adds custom fields to the options of my enum, so it looks like `[:enum {custom stuff} :a :b :c]`
```
(defenum Maybe-Yes-No
  [
   [:maybe.type/yes   "Yes"]
   [:maybe.type/no    "No"]
   [:maybe.type/maybe "Maybe"]
   ]
  )
```
 
sample code below:
important part for you

```clojure
(def web-transformer
  (mt/transformer
    {
     :name :web-ui
     :encoders (->
                 ;;(mt/-string-encoders)
                 {}
                 (assoc-in [:enum :compile] (fn [schema _]
                                              ;; we need this compiler for enums because they need to be handled differently for n-arity vs 1-arity
                                              (let [single?      (:enum/single (m/properties schema))
                                                    presentation (:web-ui/presentation (m/properties schema))]
                                                (if single?
                                                  {:enter :db/ident
                                                   :leave (comp
                                                            form.utils/tails-wrap
                                                            (partial
                                                              form.utils/selected-presentation
                                                              presentation))}
                                                  {:enter :db/ident}
                                                  ))))
                 
                 )
     }))
```


for the issue in this thread, i just put a encoder at the top level of my object, because it has the context of it's children, i do a transform for the children i want, and then the children have encoders that do transforms later on. not much different from clojure/walk.

i feel that there aren't a lot of examples that helped me figure out my solutions, i had to read a lot of the test code in malli, and it's tips docs.
