### ISSUE TITLE
Possibly faster map schemas on the JVM

### ISSUE THREAD

**Issue by bsless** [metosin/malli#455]
Hello,
I've been poking at the `-map-schema` implementation and looking for ways to make it go slightly faster and be even more amenable to the JIT compiler.
Some ideas I managed to come up with which may be worth looking into:
- `-validator` checks for `map?` first, which guarantees the object is `IPersistentMap` and `Associative`. This lets us cut down on the overhead of `find` by dispatching directly to `.entryAt()`. For  this schema `(schema [:map [:a int?] [:b int?] [:c int?]])` I measured a 2x improvement just from this single change
- another option to look at which plays into the JIT is the option of composing validators instead of iterating over them, something like `(reduce (fn [agg f] (fn [m] (and (agg m) (f m)))) validators)`. From preliminary tests it looks like it gives a speed up of at least ~20%, more for larger maps

What do you think? Does it seem viable?

**Comment by ikitommi** [comment]
oh, `find` is really slow. thanks!
