### ISSUE TITLE
malli.instrument should work with cljs

### ISSUE THREAD

**Issue by ikitommi** [metosin/malli#482]
clj-kondo file emitting & var-lookups work just now with clj.

**Comment by jeaye** [comment]
Is there any estimate for when this would be implemented? I'm currently looking to port a CLJS project from spec to malli to take advantage of some of its features and we're using instrumentation/Orchestra quite heavily.

**Comment by ikitommi** [comment]
I'm not at least working on this, looking forward to someone's PR :)

**Comment by ikitommi** [comment]
merged in master 🥳
