### ISSUE TITLE
Support JSON Schema time formats

### ISSUE THREAD

**Issue by bsless** [metosin/malli#501]
Required for #60

- [ ] date-time
- [ ] date
- [ ] time
- [ ] duration

According to the specification in:
https://datatracker.ietf.org/doc/html/rfc3339
https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.3
https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times

While date-time can be parsed to instant, date, time and duration are a bit more general.
Suggested JVM types:
- date-time: either Instant, LocalDateTime or OffsetDateTime. I suggest OffsetDateTime
- date: [LocalDate](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html)
- time: [LocalTime](https://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html)
- duration: [Duration](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html), even has a parse method compliant with the RFC

By picking the correct classes we can just use their parse methods and not have to define ad-hoc formatters.

wdyt?

**Comment by bsless** [comment]
Initial draft:

```clojure
(ns malli.time
  (:require
   [clojure.string :as str]
   [malli.core :as m])
  (:import
   (java.time Duration LocalDate OffsetDateTime OffsetTime)))

(comment
  (OffsetDateTime/parse "2016-11-01T16:51:35-01:00")
  (OffsetDateTime/parse "2016-11-01T16:51:35Z")
  (LocalDate/parse "2016-11-01")
  (OffsetTime/parse "16:51:35-01:00")
  (OffsetTime/parse "16:51:35Z")
  (Duration/parse "PT3H"))

(defn ->parser
  [f]
  (fn [x]
    (if (string? x)
      (try
        (f x)
        (catch Exception _ x))
      x)))

(defn -string->duration [x]
  (Duration/parse x))

(defn -string->offset-date-time [x]
  (OffsetDateTime/parse x))

(defn -string->local-date [x]
  (LocalDate/parse x))

(defn -string->offset-time [x]
  (OffsetTime/parse x))

(def default-date-types
  {:date {:class LocalDate :parser -string->local-date}
   :time {:class OffsetTime :parser -string->offset-time}
   :date-time {:class OffsetDateTime :parser -string->offset-date-time}
   :duration {:class Duration :parser -string->duration}})

(defn class-base-name
  [^Class c]
  (last (str/split (.getName c) #"\.")))

(defn date-schema
  ([type]
   (when-let [props (get default-date-types type)]
     (let [{klass :class parser :parser} props
           pred #(instance? klass %)
           safe-parser (->parser parser)
           message (str "Should be " (name type) " or " (class-base-name klass))]
       (m/-simple-schema
        {:type type
         :type-properties
         {:error/fn (fn [{:keys [value]} _]
                      (if (string? value)
                        (try
                          (parser value)
                          (catch Exception e (ex-message e)))
                        message))
          :decode/json {:enter safe-parser}
          :json-schema/type (name type)}
         :pred pred})))))
```

Do we need anything else?

**Comment by ikitommi** [comment]
This relates to #49. Ping @henryw374.

**Comment by henryw374** [comment]
The Duration in java.time is just a time-based thing, so e.g. `(java.time.Duration/parse "P1Y")` doesn't work. FYI this class from the extension lib combines the two java.time TemporalAmount classes https://www.threeten.org/threeten-extra/apidocs/org.threeten.extra/org/threeten/extra/PeriodDuration.html so can parse things with date and time such as `P1YT8H`. The Temporal Duration https://tc39.es/proposal-temporal/docs/duration.html does correspond to the ISO duration.

Also FYI for Temporal, there is no equivalent to OffsetTime, just an equivalent of java's LocalTime. The ZonedDateTime would fit where you have java's OffsetDateTime and PlainDate is the equivalent of java's LocalDate.

**Comment by bsless** [comment]
Can't believe I missed that
Will repost my proposal on the original issue
