### ISSUE TITLE
Show error value in humanized output

### ISSUE THREAD

**Issue by jeaye** [metosin/malli#508]
Hello! I appreciate your time in discussing this.

In re-frame apps, there is a single app-db `r/atom` which, in a real-world app, can get very, very large. Right now, if there's an issue with a value in the app I'm porting from spec to malli, the humanized output doesn't include what the incorrect value was. If I don't humanize the output, I get literally several hundred kilobytes of EDN output which is indecipherable during development.

Since this will apply to any reasonably large re-frame app, I'm proposing that we add a way to include the invalid value in the humanized form automatically. Using custom messages for this is not a viable solution, since this would need to be done for every single malli schema/validator.

Would you be open to this, or do you have another solution in mind?

**Comment by ikitommi** [comment]
Not aware that humanized error drops errors, but depends on the schema order. This was just changed in 0.6.0. Do you have an example when a error is lost?

**Comment by jeaye** [comment]
Hi @ikitommi. Have you had any chance to look at this?

**Comment by askonomm** [comment]
I'm finding the same exact warning.

**Comment by ikitommi** [comment]
fixed the arity-error

**Comment by jeaye** [comment]
Any info on the issue of including the error in the humanized output, given my stripped down example?

**Comment by ikitommi** [comment]
now reading the original text, so you want to do something like this?

```clj
(-> [:map
     [:x :int]
     [:y [:set :keyword]]
     [:z [:map
          [:a [:tuple :int :int]]]]]
    (m/explain {:x "1"
                :y #{:a "b" :c}
                :z {:a [1 "2"]}})
    (me/humanize {:wrap (juxt :value :message)}))
;{:x [["1" "should be an integer"]]
; :y #{[["b" "unknown error"]]}
; :z {:a [nil [["2" "should be an integer"]]]}}
```

**Comment by jeaye** [comment]
Thanks for taking a look.

Yep, something like that would be superb. The exact shape isn't too important, if we use a tuple or a map, but having the invalid value there for each key is crucial to making malli usable with re-frame.

**Comment by ikitommi** [comment]
It's an existing feature :)

**Comment by ikitommi** [comment]
documented this https://github.com/metosin/malli/blob/master/docs/tips.md#getting-error-values-into-humanized-result

**Comment by jeaye** [comment]
Oh, great! Thanks for adding that new tip.
