### ISSUE TITLE
Schema AST - Fast Schema Creation and Transformations

### ISSUE THREAD

**Issue by ikitommi** [metosin/malli#543]
# Problem Statement

Schema creation is still slow, should be fast(er).

# Description

Currently, Malli considers hiccup-format as the Schema AST - all Schema instance are created using `m/into-schema type props children)` and the `m/form` returns the original hiccup. This is kinda nice, enabling things like runtime schema editing, but has a big effect on Schema creation performance - especially with `EntrySchema`s, where the form needs to be parsed.

in #513, we did a lot of low hanging optimisations to make the schema creation faster (a 10x for Entry Schemas!). Still, we can make creation at least another order of magnitude faster. 

Benefits of fast schema creation:

1. inferring schemas: reading a stream of 10k entries and constructing schemas, matter a lot if it takes 10-100x or not

2. constructing large schema systems on slow runtimes (javascript, especially mobile): having a 1sec pause to initialise the schema system in unacceptable

# Considerations

We should investigate a good way to describe Schemas formally in raw-format so that we don't need to parse the syntax at runtime. There should be a way to construct a Schema from the raw-format either "I know what I'm doing" (no extra validation, the final code shipped to mobile, reading from trusted database etc) or in normal mode, where the Schema format is checked.

Some things to consider:

1. AST Syntax
2. AST<>AST and AST<>Schema tranformations

## 1) AST Syntax

Options:

1. current map-syntax
2. the compact-map syntax (#406)
3. JSON Schema -style syntax
4. Records

### 1.1) Current map-syntax

Malli already has the map-syntax, which could be used as internal format:

```clj
(def ?schema
  [:map {:title "map"}
   [:x :boolean]
   [:y {:optional true} :int]
   [:z [:map
        [:x :boolean]
        [:y {:optional true} :int]]]])

(mu/to-map-syntax ?schema)
;{:type :map,
; :properties {:title "map"}
; :children [[:x nil {:type :boolean}]
;            [:y {:optional true} {:type :int}]
;            [:z nil {:type :map
;                     :children [[:x nil {:type :boolean}] 
;                                [:y {:optional true} {:type :int}]]}]]}
```

#### Good:
* easy to implement, just add a new constructor to consume children which don't need any parsing. should be tested is it any faster
* can still be serialised

#### Bad:
* children is just a vector, adding a key would require custom functions which would need to do linear scan, which is slow
* certain schemas have special meaning for children is certain index, e.g. `:=>`, where the first child is the input & second the output
* look ugly, aesthetics matter.

=> not the way forward?

### 1.2) Compact-map syntax

As #406 describes, we could use a `compact-map` approach, where each map schema is described with it's own Malli Schema via #270. This would give use automatic 2-way conversion between optimised map-for for each individual schemas, especially good with entry- and function schemas, where children have special syntax.

```clj
(mu/to-map-syntax ?schema)
;{:type :map
; :properties {:title :map}
; :children {:x {:order 1
;                :schema {:type :boolean}}
;            :y {:order 2
;                :properties {:optional true}
;                :schema {:type :int}}
;            :z {:order 3
;                :schema {:type :map
;                         :children {:x {:order 1
;                                        :schema {:type :boolean}}
;                                    :y {:order 2
;                                        :properties {:optional true}
;                                        :schema {:type :int}}}}}}}
```

#### Good:
* clear keyword-path (e.g. `[:children :z :schema :childen :y :schema :type]`) to all structural information
* still would not lose information (e.g. order)
* no special DSL needed (could be, but basic clojure would do)
* can still be serialised

#### Bad:
* might need custom parser/unparser to be able to read/write the format
* more work than with 1 (fully generic)

### 1.3) JSON Schema -style syntax

Like 2, but with optional/required keys outside of the keys:

```clj
(mu/to-map-syntax ?schema)
;{:type :map
; :properties {:title :map}
; :required [:x :z]
; :children {:x {:schema {:type :boolean}}
;            :y {:order 2
;                :schema {:type :int}}
;            :z {:order 3
;                :schema {:type :map
;                         :required [:x]
;                         :children {:x {:order 1
;                                        :schema {:type :boolean}}
;                                    :y {:order 2
;                                        :schema {:type :int}}}}}}}
```

#### Good:
* as 2

#### Bad:
* denormalized keys

### 1.4) Records

Like 1.2 or 1.3, but with using Records. Would be a big design change.

#### Good:
* Creating a record can be faster than a map
* Records are extendable

#### Bad:
* Can't be de/serialised by default

## 2. AST<>AST and AST<>Schema tranformations

If any schema can be written into serialisable AST, we could store that for fast initialisation. 

1. Schemas could be transformed using normal ways in development and all static schemas could be optionally frozen => the transformation performance doesn't matter, as we can do that ahead of time (at dev/compile-time)
2. We could pull Schema AST out of a Schema and modify it using normal clojure functions or a DSL and create a schema out of it in the end, like `transient` + `persistent!` in Clojure
3. We could force option 2 when transforming schemas, just one DSL to transform schemas
4. We could implement normal Clojure Core protocols for `malli.core.Schema` instance and sunset the public api of `malli.util`:

```clj
(def m1 (m/schema [:map [:x :int]]))
(def m2 (m/schema [:map [:y :int]]))

(merge m1 m2)
; => [:map [:x :int] [:y :int]]

(m/ast *1)
;{:type :map
; :keys {:x {:order 1
;            :value {:type :boolean}}
;        :y {:order 2
;            :properties {:optional true}
;            :value {:type :int}}}}
```

# How to move forward

I leave this open to discussion, but my 2 cents today for implementing 1.2 and 2.1, so:

1. implement compact-maps as the AST (two-way transformation) #406
2. make schema creation fast from the AST (new `-create` method in `IntoSchema` & helpers)
3. helper or example how to freeze a fully compiled schemas system into the AST, a macro/utility to use the frozen models for quick initialisation when it matters

**Comment by ikitommi** [comment]
meanwhile:

```clj
(def ?schema
  [:map
   [:x boolean?]
   [:y {:optional true} int?]
   [:z [:map
        [:x boolean?]
        [:y {:optional true} int?]]]])

(m/form ?schema)
;[:map
; [:x boolean?]
; [:y {:optional true} int?]
; [:z [:map
;      [:x boolean?]
;      [:y {:optional true} int?]]]]

(m/ast ?schema)
;{:type :map,
; :keys {:x {:order 0
;            :value {:type boolean?}},
;        :y {:order 1, :value {:type int?}
;            :properties {:optional true}},
;        :z {:order 2,
;            :value {:type :map,
;                    :keys {:x {:order 0
;                               :value {:type boolean?}},
;                           :y {:order 1
;                               :value {:type int?}
;                               :properties {:optional true}}}}}}}

(-> ?schema
    (m/schema) ;; 3.7µs
    (m/ast) ;; 1.1µs
    (m/schema) ;; 250ns (15x)
    (m/form)
    (= (m/form ?schema)))
; => true
```

**Comment by bsless** [comment]
Some initial thoughts on maps vs. records
- Records will be fastest, both for creation and for method dispatch. Also better memory utilization
- Can still be serialized without loss of information with transit
- All records can implement a `EDN` protocol for the purposes of emitting them as data.
- records are less "data" but if everything is a dispatch on `:type` why not use the host's mechanism of dispatching on (type ,,,)?

**Comment by ikitommi** [comment]
My hypothesis is that 90%++ of the time goes elsewhere than creating / reading the AST nodes, but we should test that to be sure.

Visual comparison:

```clj
{:type :map,
 :keys {:x {:order 0
            :value {:type boolean?}},
        :y {:order 1, :value {:type int?}
            :properties {:optional true}},
        :z {:order 2,
            :value {:type :map,
                    :keys {:x {:order 0
                               :value {:type boolean?}},
                           :y {:order 1
                               :value {:type int?}
                               :properties {:optional true}}}}}}}
```

vs.

```clj
#malli.core.Map{:keys {:x c{:order 0
                                            :value {:type boolean?}},
                       :y #malli.core.Entry{:order 1, :value {:type int?}
                                            :properties {:optional true}},
                       :z #malli.core.Entry{:order 2,
                                            :value #malli.core.Map{:keys {:x #malli.core.Entry{:order 0
                                                                                               :value {:type boolean?}},
                                                                          :y #malli.core.Entry{:order 1
                                                                                               :value {:type int?}
                                                                                               :properties {:optional true}}}}}}}
```

**Comment by bsless** [comment]
Can always turn off qualified printing :thinking:

**Comment by ikitommi** [comment]
The AST syntax is consider impl detail at the moment, but the feature just landed on master. Easy to build more good stuff on top of that.

## eager parsing

```clj
(def ?schema
  [:map
   [:x boolean?]
   [:y {:optional true} int?]
   [:z [:map
        [:x boolean?]
        [:y {:optional true} int?]]]])

;; 44µs -> 2.5µs (18x)
(bench (m/schema ?schema))
```

## lazy AST

```clj
(def ast (m/ast ?schema))
;{:type :map,
; :keys {:x {:order 0, :value {:type boolean?}},
;        :y {:order 1, :value {:type int?}
;            :properties {:optional true}},
;        :z {:order 2,
;            :value {:type :map,
;                    :keys {:x {:order 0
;                               :value {:type boolean?}},
;                           :y {:order 1 
;                               :value {:type int?}
;                               :properties {:optional true}}}}}}}

;; 150ns (16x)
(p/bench (m/from-ast ast))

(-> ?schema
    (m/schema)
    (m/ast)
    (m/from-ast)
    (m/form)
    (= ?schema))
; => true
```

When you create a validator of the schema, you must realize some lazy parts of that, the ast-way is still faster (and can be optimised a lot more):

```clj
;; 3.7µs
(p/bench (m/validator (m/schema ?schema)))

;; 2.5µs
(p/bench (m/validator (m/from-ast ast)))
```

the AST is especially good for providing names for childs:

```clj
[:=> [:cat :int] :int]

;; ~= 

{:type :=>
 :input {:type :cat, :children [{:type :int}]}
 :output :int}           
 ```
