### ISSUE TITLE
General question about git usage

### ISSUE THREAD

**Issue by piotr-yuxuan** [metosin/malli#551]
Hello, thanks for this great project!

This isn't really an issue linked to this actual library but more tangential question to a prominent open-source contributor, to understand better your `git` habits and the choices you make. I've noticed that you did some force pushes on `master`. Of course it's fine but out of curiosity would you mind to elaborate on it? When does it sound needed, and what are the positive and negative side effects?

<img width="800" alt="Screenshot 2021-10-25 at 21 39 49" src="https://user-images.githubusercontent.com/3686502/138767626-0a5203e9-ffe1-4194-91d7-532f88cc05cb.png">

**Comment by ikitommi** [comment]
thanks! force push on the master is a really a bad idea, there is absolutely no good reason for doing it. Thanks for bringing it up.
