### ISSUE TITLE
Add a custom target for transforming Map keys

### ISSUE THREAD

**Issue by ikitommi** [metosin/malli#58]
e.g. virtual `:malli.core/key` schema key, that can be attached with a transformer. This allows the keys to be transformed from `kebab-case` to `snake_case` etc.

```clj
(require '[malli.core :as m])
(require '[malli.transform :as mt])

(m/transform
  [:map
   [:a-key int?]
   [:another-key string?]]
  {:a_key 1, :another_key "2"}
  (mt/key-transformer kebab-case))
; => {:a-key 1, :another-key "2"}``

**Comment by jeans11** [comment]
Do you wants use this lib? https://github.com/clj-commons/camel-snake-kebab

**Comment by ikitommi** [comment]
We don't want extra dependencies to malli, this would be just an helper to plug in map-key transformations. Clients of malli could use the `camel-snake-kebab`, been using that myself.

**Comment by jeans11** [comment]
Hi!
What do you mean with `:malli.core/key`?

**Comment by ikitommi** [comment]
Transformers are currently of type `name -> schema -> f` where `f` is the actual 1arity transformation fn. Now as transformers can be merged, it's easy to override a transformation fn for a given schema. There is no `name` for map keys, but we should have that -> if present, all map keys are transformed with it.
