### ISSUE TITLE
`decimal?` predicate schema was removed in 0.7.0?

### ISSUE THREAD

**Issue by kmwang** [metosin/malli#590]
Not sure if it's removed deliberately, or just an accident?

https://github.com/metosin/malli/commit/5deae59357b2eb3fb9890282e679bb2d7fa557e3

Thanks for the great work!

**Comment by ikitommi** [comment]
Dripped by accident. PR welcome!

**Comment by ikitommi** [comment]
and two `rational?` ?

**Comment by ikitommi** [comment]
fixed in `[metosin/malli "0.7.1"]`
