### ISSUE TITLE
Arity error in function schema

### ISSUE THREAD

**Issue by respatialized** [metosin/malli#601]
## Issue

A function schema produces an error due to overlapping arities when I attempt to use a seqex as the schema for one of the function's input arguments.

## Reproducing the bug

Attempting to create the following schema throws an error.

```clojure
(m/schema
 [:function
  [:=> [:cat [:schema [:* :int]]] :any]
  [:=> [:cat [:schema [:* :int]] :boolean] :any]])
```

```clojure
{:type :malli.core/duplicate-arities,
    :message :malli.core/duplicate-arities,
    :data
    {:infos
     [{:min 0, :arity :varargs, :input [:cat [:schema [:* :int]]], :output :any}
      {:min 1,
       :arity :varargs,
       :input [:cat [:schema [:* :int]] :boolean],
       :output :any}]}}
```

## Further information

This error occurs in spite of the fact that the input arities are independently both valid and produce the expected values when used as generators:

```clojure
(mg/generate [:cat [:schema [:cat [:* :int]]] :boolean])
;; => ((-2 2096836 3803 45 -49393) false)
(mg/generate [:cat [:schema [:cat [:* :int]]]])
;; => ((-1709 -2289 -38 3962880 -8 -948 13075997 77734 -16118422 635358 2 -1 -1))
```
@ikitommi suggested that `m/-regex-min-max` might be contributing to the error:
> Looks like `:schema` has a bug related to `m/-regex-min-max` :
>
> ```clojure
> (m/-regex-min-max
> (m/schema
>  [:cat [:schema [:* :int]]]))
> ; => {:min 0} 

Previously reported on the `#malli` channel on the Clojurians Slack.

**Comment by bbqbaron** [comment]
I ran into this just now too:

```cljs
(defn my-fn [x] 1)
(malli.core/=> my-fn [:=> [:cat [:cat :int :int]] :int])
(malli.instrument/instrument!)
(my-fn [1 2])
; :malli.core/invalid-arity
(my-fn 1 2)
; ------ WARNING - :fn-arity -----------------------------------------------------
;  Resource: <eval>:1:1
;  Wrong number of args (2) passed to engine/my-fn
; --------------------------------------------------------------------------------
```

I.e., calling it with two arguments gets past Malli, but triggers normal arity validation.

I also think it's regex min-maxing believing that nesting `:cat` doesn't affect the length of the sequence. This isn't true of nested vectors, so maybe it's a more general conceptual issue? One element with two elements in it isn't two elements.

**Comment by ikitommi** [comment]
this works in master:

```clojure
(m/schema
 [:function
  [:=> [:cat [:schema [:* :int]]] :any]
  [:=> [:cat [:schema [:* :int]] :boolean] :any]])
; => [:function [:=> [:cat [:schema [:* :int]]] :any] [:=> [:cat [:schema [:* :int]] :boolean] :any]]
```
