### ISSUE TITLE
Using malli to instrument an entire CLJS project

### ISSUE THREAD

**Issue by kovasap** [metosin/malli#654]
I have a multi-file CLJS project that I've starting adding malli schemas too, as well as [`defn` schema metadata](https://github.com/metosin/malli/blob/master/docs/function-schemas.md#function-schema-metadata).  In a single file, using `(mi/collect!) (mi/instrument!)` works great for making sure that my functions are taking and returning the proper schemas.  However, when I try to import schemas from other files it seems like the name spacing is broken.  For instance, a project like this:

```
processing.cljs
--------------------------------
(def Hiccup vector?)
(defn make-hiccup
  {:malli/schema [:=> [:cat :string] Hiccup]}
  [s]
  [:div s])
```

```
core.cljs
---------------------------------
(ns app.core
  (:require
    [app.processing]))

(mi/collect!)
(mi/instrument!)
```

Will give me this warning on compilation:

```
Use of undeclared Var app.core/Hiccup
```

It seems like my use of a var in `:malli/schema` isn't working as I would expect.  Any ideas why this could be?

**Comment by kovasap** [comment]
I'm also just looking in general for documentation on how to properly instrument my code to get `[clj-kondo` static "type" checking](https://github.com/metosin/malli/blob/master/docs/function-schemas.md#static-type-checking) working for all functions at all times when I'm developing?  For instance, is there a standard place to just leave my `(dev.start!)` call to have it work for all my code?  Do I need the `(dev.stop!)` call?

**Comment by dvingo** [comment]
Hi @kovasap I'm curious if this recent change will get rid of those warnings:
https://github.com/metosin/malli/pull/655
can you try using the latest malli code (or is this using the latest?)

there was recently some discussion on clojureverse about instrumenting cljs code as well:
https://clojureverse.org/t/problem-using-malli-clojurescript-instrumentation-and-shadow-cljs/8612

however, your code looks correct (the processing namespace is being required in core).

**Comment by kovasap** [comment]
I'm eager to try that change out, but I think I need to wait for a new malli release (or at least for your latest commit to be tagged).  Can you create a release?

**Comment by kovasap** [comment]
Thanks!  And thanks for the git example.  I was under the impression (based on my prior reading of those docs), that the revision to depend on had to be tagged; it's good to know that it doesn't have to be!

**Comment by kovasap** [comment]
Ok, I'm still having this issue with the latest version.  The core problem seems to be that malli thinks some variables I'm using to store malli spec info are in the current file's namespace, when really I imported them from other files.

**Comment by kovasap** [comment]
Actually, I think my problem only occurs when I reload my browser session.  I'll try to leave a more detailed update once I figure out exactly what's going on here.

**Comment by kovasap** [comment]
I can reproduce the error with this minimal example: https://github.com/kovasap/malli-errors-repro.  https://github.com/metosin/malli/issues/659 I think is related (these errors seem to co-occur).

**Comment by dvingo** [comment]
Thanks for the repro @kovasap  - it looks like there are some files missing though: https://github.com/kovasap/malli-errors-repro/blob/be5a59bf53e36909c87e7caf23db8af4f93e74de/src/app/core.cljs#L10

**Comment by ikitommi** [comment]
Would be awesome if there was either an example app (`/examples`?) or a guide how to work with cljs.

**Comment by kovasap** [comment]
Hey sorry about the missing file, just added!  And thanks for the code, i'll try it out next time I get the chance.

**Comment by kovasap** [comment]
It looks like you code seems to solve my https://github.com/metosin/malli/issues/659, but I still get the bad namespace warnings.

**Comment by kovasap** [comment]
It also seems like this might be blocking any kind of type checking at all, see https://github.com/kovasap/malli-errors-repro/commit/fb2a30394cc30fc0e11b086293bc07a3e5607d06

**Comment by kovasap** [comment]
That does seem to work!  I updated my example repo.  

Unfortunately, the [`a-function` function in `src/app/core.cljs`](https://github.com/kovasap/malli-errors-repro/blob/580fbcfec5e9b039ceb3135ef1e99e18750824e7/src/app/core.cljs#L10) in my repo with the incorrect spec is still not identified with those lines.  I think this might be an order-of-exectution problem - the instrumentation happens after all the code is executed, so if `a-function` isn't called again after the page is generated I wont see the error I expect.  If I put the `a-function` call right after the `instrument!` call, I do get the error as I expect ([see comments in `src/app/core.cljs`](https://github.com/kovasap/malli-errors-repro/blob/580fbcfec5e9b039ceb3135ef1e99e18750824e7/src/app/core.cljs#L37)).

This makes the instrumentation kinda unusable for normal development; so far I can't seem to get my [`a-function` call in my `home-page` function](https://github.com/kovasap/malli-errors-repro/blob/580fbcfec5e9b039ceb3135ef1e99e18750824e7/src/app/core.cljs#L20) to ever throw an error (reloading the page or editing the code and saving to trigger a hot reload don't work).

**Comment by dvingo** [comment]
ah sorry, I should have said - you have to add those lines in the `init` function as well so the instrumentation is picked up on the first render as well as subsequent ones.

**Comment by kovasap** [comment]
:facepalm: yep that works :)

**Comment by kovasap** [comment]
Although I will say that the error message is pretty hard for me to map to specific lines of code:

![image](https://user-images.githubusercontent.com/8763010/158041085-7d2f1e56-09ef-4fb0-a211-66eeca59586b.png)

**Comment by kovasap** [comment]
In practice my last comment (https://github.com/metosin/malli/issues/654#issuecomment-1066001501) is becoming quite the issue.  Should I open a new issue for this?

**Comment by dvingo** [comment]
I think a new issue is better because it's separate from the functionality not working.

**Comment by kovasap** [comment]
Ok, opened https://github.com/metosin/malli/issues/666
