### ISSUE TITLE
Clojurescript schema checking errors are difficult to map to the specific lines of failing code

### ISSUE THREAD

**Issue by kovasap** [metosin/malli#666]
See https://github.com/metosin/malli/issues/659#issue-1160480472 and https://github.com/metosin/malli/issues/654#issuecomment-1066001501 for an example.  In the Chrome console there is no direct reference to the lines of cljs code that are triggering the errors.  Inlined example:

![image](https://user-images.githubusercontent.com/8763010/158041085-7d2f1e56-09ef-4fb0-a211-66eeca59586b.png)

**Comment by kovasap** [comment]
For people who know malli better, what exactly is different about these errors when compared to those you would get when running in plain Clojure (not CLJS)?  Or are these the same errors?

I'd like to dig into this issue a big more, but am not quite sure what the expected behavior is or otherwise where to start.

**Comment by dvingo** [comment]
@kovasap when you get a chance, check out the latest code that was merged here: 
https://github.com/metosin/malli/pull/681

**Comment by kovasap** [comment]
That PR solves this problem for me.  The current state with that PR is really really good actually, nice job and thank you so much!!

I think part of my problem was that I [didn't enable custom formatters in `cljs-devtools`](https://github.com/binaryage/cljs-devtools/blob/master/docs/faq.md#why-some-custom-formatters-were-not-rendered).
