### ISSUE TITLE
mu/open-schema does not open a closed schema

### ISSUE THREAD

**Issue by bgrabow** [metosin/malli#673]
https://github.com/metosin/malli/blob/400dc0c79805028a6d85413086d4d6d627231940/src/malli/util.cljc#L139

This code appears to be a copy-paste error. It should be

```clojure
(if (-closed-map? schema options)

**Comment by bgrabow** [comment]
https://github.com/metosin/malli/blob/master/src/malli/util.cljc#L131

This line also appears to be a copy-paste error, as it reads the same as:

https://github.com/metosin/malli/blob/master/src/malli/util.cljc#L116

**Comment by vharmain** [comment]
Hi, I think functions are working as specified but the specification is not very clear. We tried to improve the docstrings to make it more clear how the functions work in different cases https://github.com/metosin/malli/issues/673. I hope this helps!
