### ISSUE TITLE
Why are `:cat` and `:=>` necessary in function schemas?

### ISSUE THREAD

**Issue by kovasap** [metosin/malli#676]
I'm using function schemas via function metadata as described at https://github.com/metosin/malli/blob/master/docs/function-schemas.md#function-schema-metadata and really like the syntax (and the fact that there are no malli dependencies unless I want to do schema checking!).  One slight annoyance I have is that the syntax seems a bit unnecessarily verbose.  For instance, it *seems* like this:

```
(defn is-5?
  {:malli/schema [:=> [:cat :number] :boolean]}
  [n]
  (= 5 n))
```

and this:

```
(defn is-5?
  {:malli/schema [[:number] :boolean]}
  [n]
  (= 5 n))
```

contain the same information.  For this example, it doesn't make a huge difference in readability, but with more complex schemas I vastly prefer the second syntax (especially when extending the schema to multiple lines that are all highly indented to account for the `:malli/schema [:=>` prefix).

Is there a reason why especially `:cat` is present in the function schema syntax?  Aren't functions always given a "`:cat`" of arguments?

As an aside, I did try to write some code that would allow me to use the second syntax, but I was having trouble figuring out how to call functions within the metadata map (to generate parts of it).  Any tips for how to do this?

**Comment by ikitommi** [comment]
Thanks for writing the issue. Thing is that `[:=> [:cat :number] :boolean]` is actually a malli schema, so you can use it as argument too, no new things to learn and tools can emit that. `[[:number] :boolean]` would be yet another syntax, saves some characters in the simple case but has less power. How would you model "int + int or string" with it? as normal malli schema, it's `[:=> [:cat :int [:alt :int :string]]]`.

It should be simple to add new syntaxes in user space, emitting the normal malli schemas, like https://github.com/teknql/aave, the lite syntax (https://github.com/metosin/malli/blob/master/src/malli/experimental/lite.cljc) & the plumatic.

**Comment by kovasap** [comment]
Ah I see, that makes sense.  I'll look into the lite code you linked if I
do end up wanting to use the terser syntax after all, but I'm not sure that
I do.

One lingering question I have is the meaning of `:cat`.  In the malli
readme it refers to some kind of sequence matching, but I get the feeling
that it is an implementation of an idea described in more detail somewhere
else.  What does cat stand for?  Is there a place I can read more about
it's meaning (and why it's used in the function schema as opposed to say,
`:tuple`)?

**Comment by ikitommi** [comment]
`:cat` stands for Concatenation, `:alt` for Alternation. Basically regex for sequences. See https://www.metosin.fi/blog/malli-regex-schemas/ for details. cheers.
