### ISSUE TITLE
Unexpected behaviour using `strip-extra-keys-transformer` with `:and` and `:or`

### ISSUE THREAD

**Issue by davidwalker** [metosin/malli#679]
I'm seeing some unexpected behaviour when using the `strip-extra-keys-transformer` with `:and` and `:or` schemas.

I have a an entity that along with as some basic properties, can have either `:a1` and `:a2` keys or a `:b` key

```clojure
(decode [:and
         [:map
          [:id string?]
          [:common1 string?]]
         [:or
          [:map
           [:a1 string?]
           [:a2 string?]]
          [:map
           [:b1 string?]]]]
        {:id "foo"
         :common1 "foo"
         :a1 "foo"
         :a2 "foo"}
        (strip-extra-keys-transformer))
;; =>  {:id foo, :common1 foo}
```

As you can see, only the common data is kept but I would expect it to keep `:a1` and `:a2` as well.

I thought I might be able to work around this by adding `:a1`, `:a2` and `:b2` to the common map as optional keys but that gives different but equally unexpected behaviour:

```clojure
(decode [:and
         [:map
          [:id string?]
          [:common1 string?]
          [:a1 {:optional true} string?]
          [:a2 {:optional true} string?]
          [:b1 {:optional true} string?]]
         [:or
          [:map
           [:a1 string?]
           [:a2 string?]]
          [:map
           [:b1 string?]]]]
        {:id "foo"
         :common1 "foo"
         :a1 "foo"
         :a2 "foo"
         :b1 "foo"}
        (strip-extra-keys-transformer))
;; =>  {:a1 foo, :a2 foo}
```

Out of interest I tried with `:and`:

```clojure
(decode [:and
         [:map
          [:id string?]
          [:common1 string?]]
         [:map
          [:a1 string?]
          [:a2 string?]]
         [:map
          [:b1 string?]]]
        {:id "foo"
         :common1 "foo"
         :a1 "foo"
         :a2 "foo"
         :b1 "foo"}
        (strip-extra-keys-transformer))
;; => {}
```

I think I understand why this is happening. It's because each :map schema is considered in turn and so the keys are progressively stripped until nothing is left.

Any suggestions on how to achieve the desired result?

**Comment by opqdonut** [comment]
I think you probably want to do something like this:
- merge all the map schemas together (with optional keys)
- use this combined-schema with strip-extra-keys-transformer
- then use your and-or schema after that to validate the decoded value

**Comment by opqdonut** [comment]
Please reopen if that doesn't work for you.

Regarding fixing strip-extra-keys-transformer: it'd be hard to know what the right thing to do would be in the general case.
