### ISSUE TITLE
Instrument on ClojureScript?

### ISSUE THREAD

**Issue by mauricioszabo** [metosin/malli#693]
I'm sorry if I'm misreading something, but so far I was not able to make `instrument!` works on ClojureScript projects. Is it not supported yet, will it be supported, etc? Is there any documentation showing how to do it?

Thanks!

**Comment by mauricioszabo** [comment]
Ok, I _kinda_ figured out that I need to upgrade to a newer SHA to make this work. But even then, I can't make it right.

So, this is an example: I added a schema:

```clojure
(def EvtSchema [:cat any? string? fn?])
(mx/defn register-provider! [{:keys [db]}
                             a :- EvtSchema])
```

And, in another namespace, I have the `(malli.dev.cljs/start!)` running when my code hot-reloads. This doesn't really works - the error I'm seeing is `"Compile Warning": Use of undeclared Var my.namepace/EvtSchema` - maybe because `EvtSchema` is on another namespace than the one I'm running `start!`?

Also, I can't seem to make the code above work. What I want is to instrument that `a` must be a vector containing anything, a string, and a function. If I do run `start!` on the same namespace, Malli will complain that I have a wrong number of arguments when I try to run `register-provider!` with two arguments

**Comment by lsenjov** [comment]
I'm playing around with this too atm

In model.query
```clj
(def Query [...])
(mx/defn get-fields :- [:set :string] [query :- Query] ...)
```

In dev.cljs, when macroexpanding (this is a snippet in a big tree of `mi/instrument!`
```clj
(set!
    model.query/get-fields
    (malli.core/-instrument
     {:schema (malli.core/function-schema [:=> [:cat Query] [:set :string]])}
     model.query/get-fields))
```

So it's not registering the function schema at compile in the same namespace, but bringing it over directly.

**Comment by lsenjov** [comment]
With a bit more of a look, the same issue also happens if you use `m/=>` instead of `mx/defn`. It does appear to be worked around by fully qualifying each var with a full namespace (use the full `:- model.query/Query` instead of just `:- Query`), but I'm still testing this.

**Comment by dvingo** [comment]
hi! there are some notes here on usage:
https://github.com/metosin/malli/blob/master/docs/clojurescript-function-instrumentation.md

And yes, this has been getting fixes recently so you'll likely need to use a recent git coordinate instead of a maven release version.
Specifically, this is the PR that fixed lots of the functionality:
https://github.com/metosin/malli/pull/681

If things still don't work, the other problem may be that I didn't take into account the `mx` style of specifying schemas, but that's just  a macro which expands to `=>` so _should_ work.

**Comment by lsenjov** [comment]
I agree, my testing `mx/defn` and `m/=>` didn't make a difference, it still macroexpanded out the same way.

I've linked a PR with a tests that fail hard (`mi/instrument!` breaks completely). The fifth set of tests (with fully qualified vars) work fine, provided instrumentation isn't broken first

**Comment by lsenjov** [comment]
I went the long way around it seems. Looking at the difference between my PR and https://github.com/metosin/malli/blob/master/test/malli/instrument/fn_schemas.cljs, the `fn-schemas` declares everything in the metadata on the defn. Using `=>` or `mx/defn` must be declaring the defn in a different way.

**Comment by dvingo** [comment]
Both styles should work. The metadata version does not register the function schema until `collect!` is called (https://github.com/metosin/malli/blob/6751b1d767f6189cde56f39c9e79e950b7264aca/src/malli/instrument/cljs.clj#L10) 
I suspect the issue you're running into is that the logic that qualifies the names used in the function schema has to be added to the `=>` macro for cljs (as is done in collect!). I will take a look into fixing this.

**Comment by lsenjov** [comment]
I've added a somewhat hacky solution to the PR @dvingo
Feel free to use/abuse/tell me what I need to fix with it.

**Comment by dvingo** [comment]
oh nice! didn't see that PR - left a comment there

**Comment by dvingo** [comment]
@mauricioszabo can you try out the latest git sha? - this should work now

**Comment by mauricioszabo** [comment]
Sure, I'll try it :)

**Comment by mauricioszabo** [comment]
It works... kinda. I'll close my issues and open a new one to track the specific problem I'm having. Thanks again!
