### ISSUE TITLE
malli.io example of "Pet" failed when executed in Clojure

### ISSUE THREAD

**Issue by minosniu** [metosin/malli#698]
Below is the code copied almost verbatim from malli.io/Pet into Clojure 1.11.1 (not Clojurescript).
```clojure
(def PetMalli
    [:schema {:registry {"Pet" [:map
                                [:type keyword?]
                                [:name string?]]
                         "Cat" [:merge
                                "Pet"
                                [:map
                                 [:type [:= "Cat"]]
                                 [:huntingSkill [:enum {:description "The measured skill for hunting"}
                                                 :clueless, :lazy, :adventurous, :aggressive]]]]
                         "Dog" [:merge
                                "Pet"
                                [:map
                                 [:type [:= "Dog"]]
                                 [:packSize [:int {:min 0,
                                                   :default 0
                                                   :description "the size of the pack the dog is from"}]]]]}}
     [:multi {:dispatch :type} "Cat" "Dog"]])

(m/validate PetMalli {:type "Cat", :name "Viivi", :huntingSkill :adventurous})
```

It produced an error message like this, which seems like a local-registry issue:
> Execution error (ExceptionInfo) at malli.core/-fail! (core.cljc:136).
:malli.core/invalid-schema {:schema :merge}

This is a rare error message that I can't find much reference in the documentation. I've noticed that the same code perhaps passes in Clojurescript. @ikitommi

**Comment by minosniu** [comment]
As @dvingo pointed out in Slack, just add the following before the schema def:
```clojure
(mr/set-default-registry! (merge (m/default-schemas) (mu/schemas)))
```

**Comment by dvingo** [comment]
It might be a good idea to link to the sources for mall.io from the website though so it's easier for others to find.

**Comment by minosniu** [comment]
> It might be a good idea to link to the sources for mall.io from the website though so it's easier for others to find.

Added link.
