### ISSUE TITLE
0.8.5 jar appears to be 0.8.4

### ISSUE THREAD

**Issue by dmcgillen** [metosin/malli#713]
I know you've only done this in the last hour so you may actually be looking at it, but I've just bumped from 0.8.4 to 0.8.5 and noticed it doesn't contain the most recently merged PR (despite Clojars saying the code tree should). On closer inspection both releases have identical SHA1 hashes for the jar, so I think something hasn't gone quite right with the release.

Thanks!

**Comment by ikitommi** [comment]
You are right. I totally forgot how to do a release and thanks to immutable deploys, finally all included in `0.8.8`. cheers.
