### ISSUE TITLE
Group level :error/message

### ISSUE THREAD

**Issue by sirmspencer** [metosin/malli#730]
I have a schema that is made up of two more primitive schema joined with :and.  I want to add an error message that is meaningful for this specific combinations of more primitive schema.  My example is simplified, and I know it will always fail.

```
(def xx
  (mc/schema [:and {:error/message "Test"}
              :string
              :int]))

(me/humanize (mc/explain xx 0))
=> ["should be a string"] 
```

Simply checking for the error message on :and and :or, like on :map or :enum, would cover most of my conditions I think.  A :group wrapper might be a more complete solution.

**Comment by ikitommi** [comment]
humanize takes `:resolve` option and there is `malli.error/-resolve-root-error` for looking the error from parent schemas:

```clojure
(-> (mc/explain xx 0)
    (me/humanize {:resolve me/-resolve-root-error}))
; => ["Test"]
```

**Comment by sirmspencer** [comment]
super duper cool.  thank you!

**Comment by sirmspencer** [comment]
FYI this function is not in the API docs.
