### ISSUE TITLE
Incorrect base case for `-some-pred`

### ISSUE THREAD

**Issue by frenchy64** [metosin/malli#751]
This should return false in Clojure. In ClojureScript it returns true.

```clojure
((-some-pred []) true) ;=> true
```

I think this line needs to be configurable.
https://github.com/metosin/malli/blob/bf92680ad76e57697261dd45c52dd31ffa9a8e1e/src/malli/impl/util.cljc#L59

I believe this is just morally incorrect since `:or` always has non-empty children (so preds are always non-empty).

**Comment by ikitommi** [comment]
or should it return `true` also in clojurescript? would be consistent with `-every-pred`. In clojure, `every-fn` and `some-fn` are not defined with zero predicates.

```clj
;; clj
((-every-pred []) 1) ; => true
((-some-pred []) 1) ; => true

;; cljs
((-every-pred []) 1) ; => true
((-some-pred []) 1) ; => false
```

**Comment by opqdonut** [comment]
The only correct choice is `(-some-pred []) ==> false`. This choice preserves two important properties:

1. `(or ((-some-pred ps) x) ((-some-pred qs) x)) === ((-some-pred (concat ps qs)) x)`
2. `((-every-pred (map complement ps)) x) === (not ((-some-pred ps) x)`

In any case, having the answers be different on clj and cljs is something that should be fixed.

**Comment by opqdonut** [comment]
Turns out Clojure does the right thing as well:
```clj
user=> (and)
true
user=> (or)
nil
```
