### ISSUE TITLE
Example of composite registry that composes the default registry with a custom one

### ISSUE THREAD

**Issue by vemv** [metosin/malli#796]
https://github.com/metosin/malli/tree/2b0c108b7c5d8b33206a4040b00dada0b103ec2c#composite-registry could be completed with an example of how to compose Malli's default registry with a custom one.

(I don't immediately know how to do that)

Thanks - V

**Comment by ikitommi** [comment]
there it is! https://github.com/metosin/malli/blob/ab0e109a2e1fd67092a07eb088c0b2f7f2181340/README.md?plain=1#L2974-L2979
