### ISSUE TITLE
More Robust Humanized Errors

### ISSUE THREAD

**Issue by ikitommi** [metosin/malli#80]
`malli.error/error-message` is great, but not complete. It should yield basic errors for all core error conditions. Fix at least the following:

* default messages for all built-in schemas:

```clj
(-> [:maybe int?]
    (m/explain "1")
    (me/humanize {:wrap :message}))
; "unknown error"
```

* error properties should be looked from father schemas in case of aggregates:

```clj
(-> [:and {:error/message "over 18"} int? [:> 18]]
    (m/explain 12)
    (me/humanize {:wrap :message}))
; "unknown error"
```

* messages for type mismatch:

```clj
(-> [:list int?]
    (m/explain #{1 2 3})
    (me/humanize {:wrap :message}))
; "unknown error"
```

**Comment by rlovtangen** [comment]
```
(-> [:and {:error/message "over 18"} int? [:> 18]]
    (m/explain 12)
    (me/humanize {:wrap :message}))
```

Is this example now supposed to return the provided message "over 18"? 
It returns only the message from `[:> 18]`: `["should be larger than 18"]`
Malli 0.9.2
