### ISSUE TITLE
Failure to decode `:enums` having keywords

### ISSUE THREAD

**Issue by billtuba** [metosin/malli#819]
Found in version :  `0.10.0`
Previously working in : `0.9.2`

Reproducible in `master` : yes
Given schema:

```
(def Test [:map-of
           [:enum {:encode/json name
                   :decode/json keyword}
            :a :b :c]
           int?])
```

When I run this:
```
(let [m (mg/generate Test)
      encoded (m/encode Test m mt/json-transformer)
      decoded (m/decode Test encoded mt/json-transformer)]
  {:generated m
   :encoded encoded
   :decoded decoded})
```
`decode` under v`0.9.2` behaves properly:
```
;; => {:generated {:b 621, :a 403, :c -14}, 
          :encoded {"b" 621, "a" 403, "c" -14},
          :decoded {:b 621, :a 403, :c -14}}
```
`decode` using v `0.10.0` does not:
```
;; => {:generated {:b -3, :a -191, :c -1}, 
          :encoded {"b" -3, "a" -191, "c" -1},
          :decoded {nil -1}} ;;; <<< here's the problem
```
[transforming_enums.clj.zip](https://github.com/metosin/malli/files/10449896/transforming_enums.clj.zip)

N.B. If remove/comment out the  `:enum/:=` entries in `-json-decoders` the code behaves as expected.

**Comment by ikitommi** [comment]
Oh, I see. This is a bug. We are composing `:map-of` transformers via `m/-comp` and it has worked before as everything was defined as a function. `:enum` is an interceptor, so we should compose it with `m/-intercepting`. This should be easy to fix. 

That said, I think the `:map-of` transformer is not working correctly anyways as it currently forcefully transforms keys into strings first, giving wrong results:

```clojure
(m/decode
 [:map-of :int :int]
 {:kikka :kukka}
 (mt/json-transformer))
; => {"kikka" :kukka}
````

Like `:or`, it should validate the results after applying key transformation, if not valid, keep the original value.

**Comment by opqdonut** [comment]
#849 is a fix for the original bug. I'll see if I can also fix the thing @ikitommi mentioned just now.

**Comment by opqdonut** [comment]
Fixed the thing ikitommi mentioned. New behaviour:
```clojure
(m/decode
 [:map-of :int :int]
 {:kikka :kukka}
 (mt/json-transformer))
; => {:kikka :kukka}
```

**Comment by billtuba** [comment]
Thanks for getting this in!
