### ISSUE TITLE
Malli generates :nilable/any which is not a valid type in clj-kondo

### ISSUE THREAD

**Issue by borkdude** [metosin/malli#821]
`:any` already includes nilables but this generates `:nilable/any`:

```
user=> (malli.clj-kondo/accept :maybe :maybe [:any] nil)
:nilable/any
```

This causes weird output with clj-kondo linting in [this issue](https://github.com/clj-kondo/clj-kondo/issues/1961).

**Comment by tvaisanen** [comment]
fixed by #843
