### ISSUE TITLE
decoding enum of keywords issue (?)

### ISSUE THREAD

**Issue by jasonjckn** [metosin/malli#830]
Is this correct behaviour? 

```
(m/decode [:enum :dev] "dev" mt/json-transformer)
;; => "dev" 
``` 

I was expecting `:dev`  (much like if you had schema `:keyword`). 

I'm new to Malli, feel free to close issue if this is intentional.

**Comment by ikitommi** [comment]
with latest version:

```clojure
(m/decode [:enum :dev] "dev" mt/json-transformer)
;; => :dev
```
