### ISSUE TITLE
Problems with `malli.core/explain`

### ISSUE THREAD

**Issue by johesoman** [metosin/malli#84]
Hi!

I believe I have found a bug. The following example behaves correctly
```
(def schema-1
  [:map
   {:name "The schema"}
   [:a int?]
   [:b int?]])

(m/validate schema-1 {:a 1337}) ;; => false
(m/explain schema-1 {:a 1337})  ;;  => {... :type :malli.core/missing-key, :malli.core/key :b}
```

But, I believe that this one doesn't. I'm expecting `explain` to give me an explanation saying that `:b` is missing.
```
(def schema-2
  [:map
   {:name "The other schema"}
   [:a int?]
   [:b int?]
   [:c {:optional true} int?]])

(m/validate schema-2 {:a 1337}) ;; => false
(m/explain schema-2 {:a 1337})  ;; => nil
```

The same goes for this example.  I'm expecting `explain` to give me an explanation saying that `:a` is missing.
```
(def regex #"b")

(def schema-3
  [:map
   {:name "Another schema"}
   [:a int?]
   [:b regex]])

(m/validate schema-3 {:a 1337}) ;; => false
(m/explain schema-3 {:b "b"})  ;; => nil
```

**Comment by ikitommi** [comment]
thanks! should be fixed now.

**Comment by johesoman** [comment]
Thanks for your quick reaction! I think you fixed the problem with the first problematic example. However, the problem with the second one seems to persist. 

In this example, when evaluating the last line, I expect `explain` to say that the value is missing the key `:a` - but instead, I get `nil`.

```
(def regex #"b")

(def schema
  [:map
   {:name "The schema"}
   [:a int?]
   [:b regex]])

(m/validate schema {:a 1337}) ;; => false
(m/explain schema {:a 1337})  ;; => {... :type malli.core/missing-key}
(m/validate schema {:b "b"})  ;; => false
(m/explain schema {:b "b"})   ;; => nil
```

**Comment by ikitommi** [comment]
Oh, there was missing an else branch in all of `:re`, `:fn` and `:maybe`. fixed all of those and added a test. Now your sample should pass. Thanks for reporting.
