### ISSUE TITLE
clj kondo linting: `error: Insufficient input.`

### ISSUE THREAD

**Issue by escherize** [metosin/malli#865]
I am seeing a lot of errors like this after rerunning malli.dev/start! on the latest version:

`src/metabase/util/honey_sql_2.clj:366:82: error: Insufficient input.` 

I think these clj-kondo errors from having the `.clj-kondo/metosin/malli-types/config.edn` file stick around. Deleting them manually seems to fix the issue.

Deleting the file manually works, but something like:

```
(.delete (io/file ".clj-kondo" "metosin" "malli-types" "config.edn"))
```

applied [in here](https://github.com/metosin/malli/commit/7f681d8ef4cdb7eb2524a4d8e8271a8aa3190c41#diff-0c47d0cd013f6cb845efdab593e740088b1cbcdb0704959422641cdffd9b7b01R159) ought to fix things.

**Comment by ikitommi** [comment]
I think this is fixed now, https://github.com/metosin/malli/blob/6653932cbb831701fde39fa014f3a26ada2dd11f/src/malli/clj_kondo.cljc#L160-L161
