### ISSUE TITLE
decode errors out when transformer throws

### ISSUE THREAD

**Issue by escherize** [metosin/malli#876]
some interesting behavior with decode. It has to do with what happens when a transformer throws.

minimal example:

```(mc/decode :sequential "32" (mtx/string-transformer))```

It came up inside a usage with an `:or` like this:

```(mc/decode [:or :sequential :int] "32" (mtx/string-transformer))```

Which you’d expect would return `32`, but no. it throws with:

```clojure.lang.ExceptionInfo: :malli.core/child-error
{:type :malli.core/child-error, :message :malli.core/child-error, :data {:type :sequential, :properties nil, :children nil, :min 1, :max 1}}
 at malli.core$_exception.invokeStatic (core.cljc:138)
    malli.core$_exception.invoke (core.cljc:136)
```

I think to fix it we'd have to either:

- make sure transformers can never throw
- handle exceptions in parent schema transforms + decode (decode needed to fix the first example)
- do both

**Comment by ikitommi** [comment]
It's not transformer, it's the schema creation (`m/decode` accepts both data and schema instances, in case of data, it call `m/schema` which fails here).

Try:

```clojure
(m/schema :sequential)
```

Instead you should:

```clojure
(m/schema [:sequential :any])
```

**Comment by escherize** [comment]
Thanks!
