### ISSUE TITLE
cljdoc API import broken since 0.10.2

### ISSUE THREAD

**Issue by KingMob** [metosin/malli#879]
https://cljdoc.org/builds/66855
https://cljdoc.org/builds/66563

It's complaining about not being able to find shadow-cljs devtools of some sort.

**Comment by ikitommi** [comment]
this is fixed now, but new similar problem with `malli.cherry` https://app.circleci.com/pipelines/github/cljdoc/builder/41333/workflows/a436b851-fe5e-4bf9-b863-79d27e4201c1/jobs/57708

**Comment by ikitommi** [comment]
should be fixed in next build: https://github.com/metosin/malli/commit/dcd3369c5473ba63a31567d7eceadcf9a7e731c1
