### ISSUE TITLE
Error when using recursive schema in seq: potentially-recursive-seqex

### ISSUE THREAD

**Issue by misterzirillo** [metosin/malli#914]
I am trying to create a schema to express a few clojure functions like so

```clojure
(def ExpressionNumericFunction
 [:and
  list?
  [:cat
   [:enum '+ '- '* '/ 'max 'min 'avg]
   [:+ [:ref ::numeric]]]])

(def ExpressionNumeric
 [:schema {:registry {::numeric
                      [:or
                       number?
                       ExpressionNumericFunction
                       ]}}
  [:ref ::numeric]])
```

However, I get the error `:malli.core/potentially-recursive-seqex` when trying to reify the schema. Indeed this is a recursive definition inside a sequence. I get the feeling this may not be supported?

**Comment by camsaul** [comment]
Try `[:schema [:ref ...]]`. Sometimes that solves it

**Comment by misterzirillo** [comment]
@camsaul I used `[:schema [:ref ...]]` in my example. Not sure what else there is to try.

**Comment by camsaul** [comment]
You need to use `:schema` in the seqex, e.g. `[:+ [:schema [:ref :numeric]]]`

**Comment by ikitommi** [comment]
Yes, Malli doesn't support recursive schemas as part of a sequence schema itself, but you can wrap the schema into `:schema` to allow recursive schemas as individual childs. Here's a definition for hiccup in [malli.io](https://malli.io/?value=%5B%3Adiv%20%7B%3Aclass%20%5B%3Afoo%20%3Abar%5D%7D%20%5B%3Ap%20%22Hello%2C%20world%20of%20data%22%5D%5D&schema=%5B%3Aschema%0A%20%7B%3Aregistry%20%7B%22hiccup%22%20%5B%3Aorn%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%3Anode%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%3Acatn%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%3Aname%20keyword%3F%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%3Aprops%20%5B%3A%3F%20%5B%3Amap-of%20keyword%3F%20any%3F%5D%5D%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%3Achildren%20%5B%3A*%20%5B%3Aschema%20%5B%3Aref%20%22hiccup%22%5D%5D%5D%5D%5D%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%3Aprimitive%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%3Aorn%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%3Anil%20nil%3F%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%3Aboolean%20boolean%3F%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%3Anumber%20number%3F%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%3Atext%20string%3F%5D%5D%5D%5D%7D%7D%0A%20%22hiccup%22%5D).
