### ISSUE TITLE
trivial: make instrumentation less spammy 

### ISSUE THREAD

**Issue by jasonjckn** [metosin/malli#920]
i have a lot of vars, and my unit test output is spammed with '..instrumented', perhaps we can move this to clojure.tools.logging trace? (or just delete it. ) 

https://github.com/metosin/malli/blob/master/src/malli/instrument.clj#L29

**Comment by jasonjckn** [comment]
In retrospect, I guess 

``` 
(with-out-str
    (malli.dev/start! {:report m.x/thrower-no-color}))
    ```

gets rid of 90% of it, so feel free to close.

**Comment by jasonjckn** [comment]
actually this trick `with-out-str` isn't working for me so well, and I don't understand why, in any case clojure.tools.logging would work better.

**Comment by aiba** [comment]
`with-out-str` doesnt' seem to work for me, I still get a zillion `"instrumented 1 vars"` strings printed to stdout.

I would love for instrumentation to be less spammy as well!
