### ISSUE TITLE
`malli.experimental.describe` descriptions of `:min` and `:max` are backwards

### ISSUE THREAD

**Issue by camsaul** [metosin/malli#924]
```clj
(require '[malli.experimental.describe :as med])

(med/describe [:string {:min 5}])
;; => "string with length <= 5"

(med/describe [:string {:max 5}])
;; => "string with length >= 5"
```

The generated descriptions have `<=` and `>=`  and mixed up. The description for `[:string {:min 5]}` (a string that has at least a minimum 5 characters, i.e. a string whose length is >= 5) is `string with length <= 5`, i.e. the string's length must be less than or equal to 5.

**Comment by ikitommi** [comment]
PR most welcome.
