### ISSUE TITLE
`strip-extra-keys-transformer` behavior changed after version 0.10.3

### ISSUE THREAD

**Issue by jahson** [metosin/malli#930]
Hi! Today I've discovered that after 0.10.3 `strip-extra-keys-transformer` changed its behavior:

`[metosin/malli "0.10.2"]`
```clojure
(m/decode
  [:map]
  {1 1, 2 "2", "3" 3, "4" "4"}
  (mt/strip-extra-keys-transformer))
; => {1 1, 2 "2", "3" 3, "4" "4"}
```

`[metosin/malli "0.10.3"]`
```clojure
(m/decode
 [:map]
 {1 1, 2 "2", "3" 3, "4" "4"}
 (mt/strip-extra-keys-transformer))
; => {}
```

It is for sure related to https://github.com/metosin/malli/blob/master/CHANGELOG.md#0103-2023-03-18 and https://github.com/metosin/malli/pull/871

**Comment by ikitommi** [comment]
in https://github.com/metosin/malli/pull/871/commits/0e5b5e3ac56479f75c812c1320ac1f1ebfba8f76:

```clojure
  (testing "extra keys from :map are stripped"
    (is (= {:x 1, :y 2}
           (m/decode
            [:map [:x :int] [:y :int]]
            {:x 1, :y 2, :z 3}
            (mt/strip-extra-keys-transformer)))))
```

so, this seems intentional, but should have been part of CHANGELOG as breaking.

not to strip keys, you can either:

```clojure
;; explicitly open map
(m/decode
 [:map {:closed false}]
 {:x 1, :y 2, :z 3}
 (mt/strip-extra-keys-transformer))
; => {:x 1, :y 2, :z 3}
```

or:

```clojure
;; anything goes
(m/decode
 [:map [::m/default :any]]
 {:x 1, :y 2, :z 3}
 (mt/strip-extra-keys-transformer))
; => {:x 1, :y 2, :z 3}
```
