### ISSUE TITLE
Support for recursive schemas

### ISSUE THREAD

**Issue by RafaeLeal** [metosin/malli#96]
Does it have support for recursive schemas?
I was trying to generate malli schemas from json-schemas (https://github.com/metosin/malli/issues/54)
But first I'd like to validate the json-schema object itself with malli, but a json schema has a lot of recursion. Do we have any way to deal with that?

**Comment by ikitommi** [comment]
Currently, no support, but there should be there is already a issue of that. https://github.com/metosin/malli/issues/20.
