### ISSUE TITLE
Feature: extend-protocol IntoSchema for java.lang.Class and protocols 

### ISSUE THREAD

**Issue by jasonjckn** [metosin/malli#961]
It would be nice if I could write code like 
``` 
(m/validate [:maybe datomic.db.Db] my-db) ;; => true 
```
(or likewise for protocols.)

and it would just work out of the box . 

If someone can confirm this is an acceptable feature, i'll write a PR. 

---

e.g. ............ (work in progress) any early feedback? 

``` 
(extend-protocol m/IntoSchema
  java.lang.Class
  (-type [^Class this] (symbol (.getName this)))
  (-type-properties [this])
  (-properties-schema [this options])
  (-children-schema [this options])
  (-into-schema [^Class this properties children options]
    (m/schema
      [:fn (merge {:error/message (str "should be an instance of java " this)} properties)
       #(clojure.core/instance? this %)]
      options)))

(m/validate String "foo") ;;=>  true 
```

protocols might be more challenging TBD.

**Comment by ikitommi** [comment]
You can already add Class -> Schema via registry:

```clojure
(m/validate [:tuple String Long]
            ["123" 123]
            {:registry (merge (m/default-schemas)
                              {String (m/-string-schema)
                               Long (m/-int-schema)})})
; => true
```

**Comment by ikitommi** [comment]
... supporting classes out of the box would be nice, but not sure then there would be at least 3 ways to describe a string:

* `string?` -> spec-like predicates
* `:string` -> malli schema
* `String` -> java Class

not sure if this makes the library easier to use.

**Comment by ikitommi** [comment]
... maybe there should be a `:instance` schema? e.g.

```clojure
(m/validate [:maybe [:instance datomic.db.Db]] my-db) ;; => true 
```

**Comment by jasonjckn** [comment]
When I started down this path, i was hoping to handle in a universal fashion, classes, interfaces & protocols, e.g. 

```
(extend-protocol m/IntoSchema
  java.lang.Class
  ....
  clojure.imaginary.Protocol
  .....
```

But protocols don't have their own Java class, rather are persistent data structures, and 

``` 
(extend-protocol m/IntoSchema
    clojure.lang.PersistentArrayMap
```
Seems a bit janky, so i'm a lot less enthusiastic my original idea 

Also, to your point about the performance of `satisfies?` , folks may want fine grained control  e.g. `[:maybe [:instance MyProtocol]]`,  `[:maybe [:satisfies MyProtocol]]`, 


I can send a PR for that if you'd like... but since this is so close to `[:fn #(satisfies? P %)]` maybe it doesn't warrant its own abstraction... am split 50/50 on this too.

**Comment by jasonjckn** [comment]
I think I realized the right solution here, it's not the most elegant code **but** it accomplishes all the performance objectives and 'open polymorphism' of protocols. Just make `into-schema?` a protocol instead of calling `satisfies?` or even `instance?` 

<img width="725" alt="image" src="https://github.com/metosin/malli/assets/550839/bb63da6c-ced4-4bab-8ba3-76009fd85476">
 
 Thus any time you extend the protocol m/IntoSchema, you would also have to extend m/SupportsIntoSchema, 
 
 I think if you go this route, it may simplify `into-schema` function as well, because you'll be able to do `(extend-protocol m/IntoSchema IPersistentVector` instead  of handling it as a special case .... but if you don't care for this, no worries, either-way this is a good idea IMO.

**Comment by jasonjckn** [comment]
going to close this, because i'm personally not that interested anymore, but I can send a PR if someone else really wants this. 

Please see https://github.com/metosin/malli/issues/960 though, i'm still interested in the capability of -being able to do this-.
