### ISSUE TITLE
All schemas should target transformations to themselves

### ISSUE THREAD

**Issue by ikitommi** [metosin/malli#98]
Currently, the following Schemas do not have `this` as a transformation target, e.g. adding a transformation hint via properties will not work with these:

* [x] `:and`, `:or`
* [x] `:map-of`
* [x] `:vector`, `:list`, `:set`
* [x] `:tuple`
* [x] `:enum`
* [x] `:re`
* [x] `:fn`
* [x] `:maybe`

This doesn't work currently (`:and` doesn't have a transformation target):

```clj
(m/encode
   [:and {:decode/string '(constantly str/upper)} string?]
   "kikka"
    mt/string-transformer)
; => "kikka"
```

But this does (`string?` has):

```clj
(m/encode
   [string? {:decode/string '(constantly str/upper)}]
   "kikka"
    mt/string-transformer)
; => "KIKKA"
```

As transformation is a primary use case, we should unroll the functions for performance. @jeans11 did this already for `:map`.

**Comment by boxxxie** [comment]
when is `m/encode`? i think it may have moved to a different namespace from core. i can't run the examples
