### ISSUE TITLE
json-transformer should coerce doubles with zero fractional part to longs

### ISSUE THREAD

**Issue by irigarae** [metosin/malli#986]
Per the [json schema specification](https://json-schema.org/understanding-json-schema/reference/numeric#integer) integers also accept floating point numbers with zero fractional part:

> Numbers with a zero fractional part are considered integers:
> ```
> 1.0
> ;; compliant with schema { "type": "integer" }
> ```

This breaks a bit when decoding with a json-transformer.

```clojure
(m/validate :int (m/decode :int 3.0 mt/json-transformer))
#_=> false
```

I think it would be a nice addition to the json-decoders:

```clojure
;; just an example, not taking into account clj/cljs nor NaN, etc.
(defn -float->long [x]
  (if (and (float? x) (zero? (rem x 1)))
    (long x)
    x))
(m/validate :int (m/decode :int 3.0 (mt/transformer {:decoders {:int -float->long}})))
#_=> true
;; same example
(m/decode [:int {:decode/json -float->long}] 3.0 mt/json-transformer) #_=> 3
(m/decode [:int {:decode/json -float->long}] 3.2 mt/json-transformer) #_=> 3.2
```

**Comment by ikitommi** [comment]
thanks for the info, this should be fixed.
