### ISSUE TITLE
m/deref-recursive doesn't play nice with :merge schema

### ISSUE THREAD

**Issue by irigarae** [metosin/malli#997]
Hi, I noticed the newly released deref-recursive doesn't give what I would expect for `:merge` schemas. Bug? Or deref-recursive is intended for something else?

```clojure
(m/deref
 [:merge
  [:map [:x :int]]
  [:map [:y :int]]]
 {:registry (merge (m/default-schemas) (mu/schemas))})
#_=> [:map [:x :int] [:y :int]]

(m/deref-all
 [:merge
  [:map [:x :int]]
  [:map [:y :int]]]
 {:registry (merge (m/default-schemas) (mu/schemas))})
#_=> [:map [:x :int] [:y :int]]

(m/deref-recursive
 [:merge
  [:map [:x :int]]
  [:map [:y :int]]]
 {:registry (merge (m/default-schemas) (mu/schemas))})
#_=> [:map [:x :int]]
```

**Comment by ikitommi** [comment]
Ok, this is a bug in either `:merge` or in the new util. Thanks for reporting.

**Comment by ikitommi** [comment]
Ok, this is create - https://github.com/metosin/malli/blob/master/src/malli/core.cljc#L2321 takes just `first`. The utility schemas have multiple children.
